/**
 * @file web_assets.c
 * @brief Embedded Web Page Assets Implementation (Auto-generated)
 * @author OpenVela Contest 2026 Team 145
 */

#include "web_assets.h"
#include <string.h>

static const char s_setup_html[] =
    "<!DOCTYPE html><html lang=\"zh-CN\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\""
    "width=device-width, initial-scale=1.0\"><title>Gemini-S1 硬件热点配网</title><style>:root {--bg: #080c14;-"
    "-card: #101726;--border: #1c2a44;--accent: #00e5ff;--accent-sub: #00ff88;--warn: #ffb700;--text: #e6"
    "edf3;--muted: #8b9eb5;}body {margin: 0;padding: 24px 16px;background: var(--bg);color: var(--text);f"
    "ont-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, sans-serif;}.box {max-width: 44"
    "0px;margin: 0 auto;background: var(--card);border: 1px solid var(--border);border-radius: 16px;paddi"
    "ng: 24px;box-shadow: 0 12px 32px rgba(0, 0, 0, 0.5);position: relative;}.box::before {content: '';po"
    "sition: absolute;top: 0;left: 0;right: 0;height: 3px;background: linear-gradient(90deg, var(--accent"
    "), var(--accent-sub));border-radius: 16px 16px 0 0;}h1 {color: var(--accent);font-size: 20px;margin:"
    " 0 0 6px;text-align: center;display: flex;align-items: center;justify-content: center;gap: 8px;}p {f"
    "ont-size: 13px;color: var(--muted);line-height: 1.5;margin: 0 0 16px;text-align: center;}.scan-bar {"
    "display: flex;justify-content: space-between;align-items: center;margin-top: 14px;margin-bottom: 6px"
    ";}.scan-title {font-size: 13px;font-weight: 700;color: var(--accent);display: flex;align-items: cent"
    "er;gap: 6px;}.scan-btn {background: #182842;border: 1px solid #233b63;color: var(--accent);padding: "
    "4px 12px;border-radius: 14px;font-size: 12px;font-weight: 600;cursor: pointer;transition: 0.2s;}.sca"
    "n-btn:hover {background: #22375a;}label {font-size: 12px;color: var(--muted);font-weight: 600;margin"
    "-top: 12px;display: block;}input, select {width: 100%;box-sizing: border-box;padding: 11px;margin-to"
    "p: 6px;border-radius: 8px;border: 1px solid var(--border);background: #090d16;color: #fff;font-size:"
    " 13px;font-family: inherit;}input:focus, select:focus {border-color: var(--accent);outline: none;}.w"
    "ifi-badges {display: flex;flex-wrap: wrap;gap: 6px;margin-top: 8px;}.wifi-badge {background: #0a0f1c"
    ";border: 1px solid rgba(255, 255, 255, 0.06);padding: 6px 10px;border-radius: 6px;font-size: 12px;cu"
    "rsor: pointer;display: flex;align-items: center;gap: 4px;color: #c0d2e8;transition: 0.2s;}.wifi-badg"
    "e:hover {border-color: var(--accent);color: var(--accent);background: #131d30;}button.submit-btn {wi"
    "dth: 100%;background: var(--accent);color: #04060a;border: none;border-radius: 8px;padding: 13px;fon"
    "t-size: 15px;font-weight: bold;cursor: pointer;margin-top: 20px;transition: 0.2s;}button.submit-btn:"
    "hover {background: #33ebff;transform: translateY(-1px);}.tip {background: #0c1422;border-left: 3px s"
    "olid var(--accent);padding: 10px 12px;margin-top: 16px;border-radius: 6px;font-size: 12px;color: #a0"
    "b4cc;line-height: 1.5;}.status-pill {font-size: 11px;padding: 2px 6px;border-radius: 10px;background"
    ": #182842;color: var(--accent-sub);}/* 全屏科技感加载与状态反馈模态框 */.modal-overlay {position: fixed;top: 0;left"
    ": 0;right: 0;bottom: 0;background: rgba(4, 7, 13, 0.88);backdrop-filter: blur(10px);-webkit-backdrop"
    "-filter: blur(10px);display: flex;align-items: center;justify-content: center;z-index: 9999;opacity:"
    " 0;pointer-events: none;transition: opacity 0.3s ease;padding: 16px;}.modal-overlay.active {opacity:"
    " 1;pointer-events: auto;}.modal-card {max-width: 400px;width: 100%;background: #0d1424;border: 1px s"
    "olid #1c2b45;border-radius: 18px;padding: 28px 24px;text-align: center;box-shadow: 0 20px 50px rgba("
    "0, 229, 255, 0.15);position: relative;}.radar-box {width: 76px;height: 76px;margin: 0 auto 18px;posi"
    "tion: relative;display: flex;align-items: center;justify-content: center;}.radar-ring {position: abs"
    "olute;inset: 0;border-radius: 50%;border: 2px solid transparent;border-top-color: var(--accent);bord"
    "er-right-color: var(--accent-sub);animation: radar-spin 1.2s cubic-bezier(0.68, -0.55, 0.27, 1.55) i"
    "nfinite;}.radar-pulse {position: absolute;inset: -6px;border-radius: 50%;border: 1px solid rgba(0, 2"
    "29, 255, 0.2);animation: radar-pulse 2s ease-out infinite;}.radar-icon {font-size: 30px;z-index: 2;}"
    "@keyframes radar-spin {from { transform: rotate(0deg); }to { transform: rotate(360deg); }}@keyframes"
    " radar-pulse {0% { transform: scale(0.9); opacity: 0.8; }100% { transform: scale(1.3); opacity: 0; }"
    "}.modal-title {font-size: 18px;font-weight: bold;color: #fff;margin-bottom: 8px;}.modal-desc {font-s"
    "ize: 13px;color: var(--muted);line-height: 1.6;margin-bottom: 20px;}.ip-display-card {background: #0"
    "70b14;border: 1px solid #00ff88;border-radius: 10px;padding: 12px;margin-bottom: 16px;display: none;"
    "}.ip-label {font-size: 11px;color: var(--muted);margin-bottom: 4px;text-transform: uppercase;letter-"
    "spacing: 0.5px;}.ip-value {font-size: 20px;font-weight: 800;font-family: monospace;color: var(--acce"
    "nt-sub);letter-spacing: 1px;}.action-btn {display: inline-block;width: 100%;box-sizing: border-box;b"
    "ackground: var(--accent-sub);color: #040810;font-size: 14px;font-weight: bold;padding: 11px;border-r"
    "adius: 8px;border: none;cursor: pointer;text-decoration: none;transition: 0.2s;}.action-btn:hover {b"
    "ackground: #33ff9f;transform: translateY(-1px);}.cancel-btn {margin-top: 12px;background: transparen"
    "t;border: none;color: var(--muted);font-size: 12px;cursor: pointer;text-decoration: underline;}</sty"
    "le></head><body><div class=\"box\"><div style=\"display: flex; background: #0a0f1d; border: 1px soli"
    "d #1a273f; border-radius: 10px; padding: 3px; margin-bottom: 16px; gap: 4px;\"><a href=\"ble_setup.h"
    "tml\" style=\"flex: 1; text-align: center; padding: 7px 10px; font-size: 12px; font-weight: 600; bor"
    "der-radius: 8px; color: var(--accent); text-decoration: none; display: flex; align-items: center; ju"
    "stify-content: center; gap: 4px; transition: 0.2s;\">⚡ 蓝牙免切网配网 (推荐)</a><div style=\"flex: 1; text-al"
    "ign: center; padding: 7px 10px; font-size: 12px; font-weight: 600; border-radius: 8px; background: r"
    "gba(0, 229, 255, 0.15); color: #fff; border: 1px solid rgba(0, 229, 255, 0.3); display: flex; align-"
    "items: center; justify-content: center; gap: 4px;\">📡 传统热点配网</div></div><h1>📡 Gemini-S1 硬件热点配网</h1><"
    "p>设备处于 SoftAP 独立热点模式。请搜索并选择周边 Wi-Fi 连入网络；联网后可在控制中心或伴侣看板中自由配置 Agent 模型与桌面玩法。</p><div class=\"scan-bar"
    "\"><span class=\"scan-title\">📶 周边 Wi-Fi 热点</span><button class=\"scan-btn\" onclick=\"scanWifi()\">"
    "🔄 刷新扫描</button></div><select id=\"wifiSelect\" onchange=\"onSelectChange()\"><option value=\"\">⏳ 正在"
    "搜索周边 Wi-Fi...</option></select><div class=\"wifi-badges\" id=\"quickList\"></div><div id=\"manualBox"
    "\" style=\"display:none;\"><label>手动输入 SSID:</label><input id=\"ssid\" type=\"text\" placeholder=\"输"
    "入无线网络名称 (SSID)\"></div><label>Wi-Fi 密码 (PSK):</label><input id=\"psk\" type=\"password\" placeholder"
    "=\"请输入密码 (开放网络留空)\"><div id=\"authTip\" style=\"font-size:11px; color:#00ff88; margin-top:4px; displ"
    "ay:none;\"></div><button class=\"submit-btn\" onclick=\"connectWifi()\">🚀 保存凭证并连接 Wi-Fi</button><div"
    " class=\"tip\" id=\"msg\">💡 连接后设备将自动切换并向路由器获取局域网 IP。设备正面屏幕将实时弹出连网动效与微胶囊 IP，同时此网页也将自动同步展示新 IP。</div><"
    "/div><div class=\"modal-overlay\" id=\"connectingModal\"><div class=\"modal-card\"><div class=\"rada"
    "r-box\"><div class=\"radar-pulse\" id=\"radarPulse\"></div><div class=\"radar-ring\" id=\"radarRing\""
    "></div><div class=\"radar-icon\" id=\"radarIcon\">📡</div></div><div class=\"modal-title\" id=\"modal"
    "Title\">正在连接无线网络...</div><div class=\"modal-desc\" id=\"modalDesc\">正在将 Wi-Fi 凭证下发给设备硬件，并向路由器发起 DHCP"
    " 握手以获取局域网 IP 地址。<br>请保持当前页面开启...</div><div class=\"ip-display-card\" id=\"ipCard\"><div class=\"ip-l"
    "abel\">设备新局域网 IP 地址</div><div class=\"ip-value\" id=\"ipVal\">0.0.0.0</div></div><a id=\"btnGoDashbo"
    "ard\" class=\"action-btn\" style=\"display:none;\" href=\"#\">🎉 打开极客伴侣看板</a><button class=\"cancel-b"
    "tn\" id=\"btnCloseModal\" onclick=\"closeModal()\" style=\"display:none;\">关闭此弹窗</button></div></div"
    "><script>let scanData = [];let pollTimer = null;let pollCount = 0;let targetSsid = '';function scanW"
    "ifi() {const sel = document.getElementById('wifiSelect');sel.innerHTML = '<option value=\"\">⏳ 正在搜索周"
    "边 Wi-Fi...</option>';document.getElementById('quickList').innerHTML = '';fetch('/api/wifi/scan').the"
    "n(r => r.json()).then(d => {scanData = d.aps || [];sel.innerHTML = '';const qk = document.getElement"
    "ById('quickList');if (scanData.length === 0) {sel.innerHTML = '<option value=\"__manual__\">未搜到热点 - "
    "已展开手动输入 SSID</option>';document.getElementById('manualBox').style.display = 'block';return;}sel.inne"
    "rHTML = '<option value=\"\">-- 请选择 Wi-Fi 热点 (' + scanData.length + '个可用) --</option>';scanData.forEa"
    "ch(ap => {const opt = document.createElement('option');opt.value = ap.ssid;opt.text = '📶 ' + ap.ssid"
    " + ' (' + ap.rssi + 'dBm · ' + ap.auth + ')';sel.appendChild(opt);const bd = document.createElement("
    "'div');bd.className = 'wifi-badge';bd.innerHTML = '📶 ' + ap.ssid + ' <span class=\"status-pill\">' +"
    " ap.auth + '</span>';bd.onclick = () => {sel.value = ap.ssid;onSelectChange();};qk.appendChild(bd);}"
    ");const mOpt = document.createElement('option');mOpt.value = '__manual__';mOpt.text = '➕ 手动输入隐藏 Wi-F"
    "i...';sel.appendChild(mOpt);}).catch(e => {sel.innerHTML = '<option value=\"__manual__\">扫描超时 - 已展开手"
    "动输入 SSID</option>';document.getElementById('manualBox').style.display = 'block';});}function onSelec"
    "tChange() {const val = document.getElementById('wifiSelect').value;const mb = document.getElementByI"
    "d('manualBox');const tip = document.getElementById('authTip');if (val === '__manual__') {mb.style.di"
    "splay = 'block';tip.style.display = 'none';} else {mb.style.display = 'none';document.getElementById"
    "('ssid').value = val;const ap = scanData.find(x => x.ssid === val);if (ap && ap.auth === 'OPEN') {ti"
    "p.innerText = '● 该网络为开放免密网络，密码可留空直接连接';tip.style.display = 'block';document.getElementById('psk').va"
    "lue = '';} else {tip.style.display = 'none';}}}function showModal(title, desc, icon) {const modal = "
    "document.getElementById('connectingModal');document.getElementById('modalTitle').innerText = title;d"
    "ocument.getElementById('modalDesc').innerHTML = desc;if (icon) document.getElementById('radarIcon')."
    "innerText = icon;modal.classList.add('active');}function closeModal() {if (pollTimer) clearInterval("
    "pollTimer);document.getElementById('connectingModal').classList.remove('active');}function connectWi"
    "fi() {let s = document.getElementById('wifiSelect').value;if (s === '__manual__' || !s) {s = documen"
    "t.getElementById('ssid').value.trim();}if (!s) {alert('请先选择或输入 Wi-Fi 名称！');return;}targetSsid = s;co"
    "nst p = document.getElementById('psk').value;showModal('正在连接无线网络...','已向设备下发网络凭证，正在尝试加入 <b>' + s + '"
    "</b> 并通过 DHCP 获取 IP 地址。<br>请稍候，设备屏幕也将同步显示连网动效...','📡');document.getElementById('ipCard').style.displ"
    "ay = 'none';document.getElementById('btnGoDashboard').style.display = 'none';document.getElementById"
    "('btnCloseModal').style.display = 'none';fetch('/api/wifi/connect', {method: 'POST',headers: {'Conte"
    "nt-Type': 'application/json'},body: JSON.stringify({ssid: s, psk: p})}).then(r => r.json()).then(d ="
    "> {startPollingStatus();}).catch(e => {/* 射频切换可能瞬间切断 SoftAP，直接启动轮询检测 */startPollingStatus();});}func"
    "tion startPollingStatus() {if (pollTimer) clearInterval(pollTimer);pollCount = 0;pollTimer = setInte"
    "rval(() => {pollCount++;/* 轮询 Wi-Fi 与系统状态 */fetch('/api/wifi/status', {cache: 'no-store'}).then(r =>"
    " r.json()).then(d => {checkConnectionResult(d);}).catch(() => {/* 如果 wifi/status 访问失败，尝试备用 /api/stat"
    "us */fetch('/api/status', {cache: 'no-store'}).then(r => r.json()).then(d => {const net = d.network "
    "|| {};checkConnectionResult({is_connected: net.connected || false,ip: net.ip || '',mode: net.mode ||"
    " '',ssid: net.ssid || ''});}).catch(() => {/* 超过 15 次 (约 18 秒) 且无法连接 192.168.4.1，说明手机从 SoftAP 断开 */i"
    "f (pollCount > 15) {handleSoftApDisconnected();}});});/* 超时保护 (35秒) */if (pollCount > 28) {clearInte"
    "rval(pollTimer);handleSoftApDisconnected();}}, 1200);}function checkConnectionResult(d) {const isCon"
    "nected = d.is_connected || d.mode === 'STA_CONNECTED';const ip = d.ip;if (isConnected && ip && ip !="
    "= '0.0.0.0' && !ip.startsWith('192.168.4.')) {if (pollTimer) clearInterval(pollTimer);document.getEl"
    "ementById('radarRing').style.animation = 'none';document.getElementById('radarRing').style.borderCol"
    "or = 'var(--accent-sub)';document.getElementById('radarIcon').innerText = '✅';document.getElementByI"
    "d('modalTitle').innerText = '🎉 Wi-Fi 连接成功！';document.getElementById('modalDesc').innerHTML ='设备已成功加入"
    "网络 <b>' + (d.ssid || targetSsid) + '</b>！<br>' +'设备正面微胶囊已实时更新 IP。请将手机/电脑连入同一 Wi-Fi，即可无缝进入极客伴侣看板。';do"
    "cument.getElementById('ipVal').innerText = ip;document.getElementById('ipCard').style.display = 'blo"
    "ck';const dashUrl = 'http://' + ip + ':8080/';const btnDash = document.getElementById('btnGoDashboar"
    "d');btnDash.href = dashUrl;btnDash.style.display = 'inline-block';document.getElementById('btnCloseM"
    "odal').style.display = 'inline-block';/* 倒计时 3 秒后尝试自动跳转 */let countdown = 3;btnDash.innerText = '🚀 立"
    "即进入极客伴侣看板 (' + countdown + 's)';const cTimer = setInterval(() => {countdown--;if (countdown > 0) {bt"
    "nDash.innerText = '🚀 立即进入极客伴侣看板 (' + countdown + 's)';} else {clearInterval(cTimer);btnDash.innerTex"
    "t = '🚀 正在跳转至 ' + ip + '...';window.location.href = dashUrl;}}, 1000);}}function handleSoftApDisconne"
    "cted() {if (pollTimer) clearInterval(pollTimer);document.getElementById('radarIcon').innerText = 'ℹ️"
    "';document.getElementById('radarRing').style.animation = 'none';document.getElementById('radarRing')"
    ".style.borderColor = 'var(--warn)';document.getElementById('modalTitle').innerText = '📡 凭证已下发，设备正步进连"
    "网';document.getElementById('modalDesc').innerHTML ='设备已关闭 SoftAP 独立热点并切换至联网模式。<br><br>' +'<b>请直接观察设备"
    "正面屏幕：</b><br>' +'屏幕已自动切入【步进配网状态机】，实时展示：<br>' +'① 关闭独立热点 [✓] ➔ ② 关联路由器 [⟳] ➔ ③ 申请 DHCP IP [⟳]<br><br>"
    "' +'• <b>配网成功</b>：屏幕将展示分配到的局域网 IP 及伴侣看板入口；<br>' +'• <b>配网失败</b>：屏幕将弹出超时/密码错误警告，并自动恢复热点供重试。';document"
    ".getElementById('btnCloseModal').style.display = 'inline-block';document.getElementById('btnCloseMod"
    "al').innerText = '已了解，查看设备正面屏幕';}scanWifi();</script></body></html>";

static const char s_ble_setup_html[] =
    "<!DOCTYPE html><html lang=\"zh-CN\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\""
    "width=device-width, initial-scale=1.0\"><title>Phoenix Agent - Web 蓝牙极速配网中心</title><style>:root {--b"
    "g: #060913;--card-bg: rgba(13, 21, 39, 0.78);--card-border: rgba(0, 240, 255, 0.22);--card-border-ho"
    "ver: rgba(0, 240, 255, 0.55);--accent: #00f0ff;--accent-sub: #00ff88;--warn: #ffb700;--danger: #ff47"
    "57;--text: #e6edf3;--muted: #8b9eb5;--input-bg: #090e1c;--input-border: #1c2b45;}* {box-sizing: bord"
    "er-box;margin: 0;padding: 0;}body {min-height: 100vh;background: radial-gradient(circle at top right"
    ", #101d36 0%, #060913 60%);color: var(--text);font-family: -apple-system, BlinkMacSystemFont, \"Sego"
    "e UI\", Roboto, \"PingFang SC\", \"Hiragino Sans GB\", \"Microsoft YaHei\", sans-serif;padding: 32px"
    " 16px;display: flex;flex-direction: column;align-items: center;position: relative;overflow-x: hidden"
    ";}/* 赛博网格与环境微光 */body::before {content: '';position: fixed;top: 0; left: 0; right: 0; bottom: 0;back"
    "ground: linear-gradient(rgba(0, 240, 255, 0.03) 1px, transparent 1px),linear-gradient(90deg, rgba(0,"
    " 240, 255, 0.03) 1px, transparent 1px);background-size: 32px 32px;pointer-events: none;z-index: 0;}."
    "container {width: 100%;max-width: 480px;position: relative;z-index: 1;}/* 顶部横幅 */.top-badge {display"
    ": inline-flex;align-items: center;gap: 6px;padding: 4px 12px;background: rgba(0, 240, 255, 0.1);bord"
    "er: 1px solid rgba(0, 240, 255, 0.3);border-radius: 20px;font-size: 11px;color: var(--accent);font-w"
    "eight: 600;text-transform: uppercase;letter-spacing: 0.5px;margin-bottom: 12px;}.main-card {backgrou"
    "nd: var(--card-bg);backdrop-filter: blur(16px);-webkit-backdrop-filter: blur(16px);border: 1px solid"
    " var(--card-border);border-radius: 20px;padding: 28px 24px;box-shadow: 0 16px 40px rgba(0, 0, 0, 0.6"
    "), 0 0 24px rgba(0, 240, 255, 0.08);position: relative;overflow: hidden;transition: border-color 0.3"
    "s ease;}.main-card::before {content: '';position: absolute;top: 0; left: 0; right: 0;height: 3px;bac"
    "kground: linear-gradient(90deg, var(--accent), var(--accent-sub));}.title-row {text-align: center;ma"
    "rgin-bottom: 20px;}.title-row h1 {font-size: 22px;font-weight: 700;color: #fff;display: flex;align-i"
    "tems: center;justify-content: center;gap: 10px;}.title-row p {font-size: 13px;color: var(--muted);ma"
    "rgin-top: 6px;line-height: 1.5;}/* 模式切换胶囊 */.mode-switch {display: flex;background: #090e1c;border: "
    "1px solid #1a273f;border-radius: 12px;padding: 3px;margin-bottom: 22px;gap: 4px;}.mode-tab {flex: 1;"
    "text-align: center;padding: 8px 12px;font-size: 12px;font-weight: 600;border-radius: 9px;color: var("
    "--muted);cursor: pointer;text-decoration: none;transition: all 0.2s ease;display: flex;align-items: "
    "center;justify-content: center;gap: 6px;}.mode-tab.active {background: linear-gradient(135deg, rgba("
    "0, 240, 255, 0.2), rgba(0, 255, 136, 0.15));color: #fff;border: 1px solid rgba(0, 240, 255, 0.4);box"
    "-shadow: 0 2px 8px rgba(0, 240, 255, 0.15);}/* 蓝牙连接区 */.ble-status-box {background: rgba(9, 14, 28, "
    "0.7);border: 1px dashed var(--card-border);border-radius: 14px;padding: 18px;text-align: center;marg"
    "in-bottom: 20px;position: relative;transition: all 0.3s ease;}.ble-status-box.connected {border-styl"
    "e: solid;border-color: var(--accent-sub);background: rgba(0, 255, 136, 0.05);}.ble-icon-circle {widt"
    "h: 52px;height: 52px;border-radius: 50%;background: rgba(0, 240, 255, 0.1);border: 2px solid var(--a"
    "ccent);display: flex;align-items: center;justify-content: center;margin: 0 auto 12px;font-size: 24px"
    ";box-shadow: 0 0 16px rgba(0, 240, 255, 0.3);transition: all 0.3s ease;}.ble-status-box.connected .b"
    "le-icon-circle {border-color: var(--accent-sub);background: rgba(0, 255, 136, 0.15);box-shadow: 0 0 "
    "16px rgba(0, 255, 136, 0.35);}.ble-title {font-size: 15px;font-weight: 600;color: #fff;margin-bottom"
    ": 4px;}.ble-desc {font-size: 12px;color: var(--muted);line-height: 1.4;margin-bottom: 12px;}.btn {di"
    "splay: inline-flex;align-items: center;justify-content: center;gap: 8px;width: 100%;padding: 12px 18"
    "px;font-size: 14px;font-weight: 600;border-radius: 12px;border: none;cursor: pointer;transition: all"
    " 0.2s ease;text-decoration: none;}.btn-ble {background: linear-gradient(135deg, #00b4d8, #0077b6);co"
    "lor: #fff;box-shadow: 0 4px 16px rgba(0, 180, 216, 0.35);}.btn-ble:hover {background: linear-gradien"
    "t(135deg, #00c6eb, #0088cc);transform: translateY(-1px);box-shadow: 0 6px 20px rgba(0, 180, 216, 0.5"
    ");}.btn-submit {background: linear-gradient(135deg, var(--accent), #00a8cc);color: #060913;font-weig"
    "ht: 700;margin-top: 16px;box-shadow: 0 4px 16px rgba(0, 240, 255, 0.35);}.btn-submit:hover:not(:disa"
    "bled) {background: linear-gradient(135deg, #33f3ff, #00c4ec);transform: translateY(-1px);box-shadow:"
    " 0 6px 22px rgba(0, 240, 255, 0.55);}.btn-submit:disabled {opacity: 0.45;cursor: not-allowed;filter:"
    " grayscale(0.8);}/* 双向全双工指示灯与同步徽章 */.duplex-bar {display: inline-flex;align-items: center;gap: 5px;f"
    "ont-size: 10px;font-family: monospace;font-weight: 700;}.led-pill {display: inline-flex;align-items:"
    " center;padding: 1px 5px;border-radius: 4px;background: #090e1c;border: 1px solid #1c2b45;color: var"
    "(--muted);transition: all 0.1s ease;}.led-pill.active-tx {background: rgba(0, 240, 255, 0.35);border"
    "-color: var(--accent);color: var(--accent);box-shadow: 0 0 10px rgba(0, 240, 255, 0.8);}.led-pill.ac"
    "tive-rx {background: rgba(0, 255, 136, 0.35);border-color: var(--accent-sub);color: var(--accent-sub"
    ");box-shadow: 0 0 10px rgba(0, 255, 136, 0.8);}.sync-badge {display: inline-flex;align-items: center"
    ";gap: 6px;padding: 4px 10px;border-radius: 8px;background: rgba(0, 255, 136, 0.1);border: 1px solid "
    "rgba(0, 255, 136, 0.3);color: var(--accent-sub);font-size: 11px;font-weight: 600;margin-top: 8px;}/*"
    " 表单控件 */.form-group {margin-top: 14px;}.form-label {display: flex;justify-content: space-between;ali"
    "gn-items: center;font-size: 12px;font-weight: 600;color: var(--muted);margin-bottom: 6px;}.form-labe"
    "l span.req {color: var(--accent);}.input-wrap {position: relative;}input, select, textarea {width: 1"
    "00%;background: var(--input-bg);border: 1px solid var(--input-border);color: #fff;padding: 10px 14px"
    ";font-size: 13px;border-radius: 10px;outline: none;transition: all 0.2s ease;font-family: inherit;}i"
    "nput:focus, select:focus, textarea:focus {border-color: var(--accent);box-shadow: 0 0 10px rgba(0, 2"
    "40, 255, 0.25);}/* 高级折叠面板 */.advanced-toggle {display: flex;align-items: center;justify-content: spa"
    "ce-between;margin-top: 18px;padding-top: 14px;border-top: 1px solid #16243b;cursor: pointer;user-sel"
    "ect: none;}.advanced-toggle span {font-size: 12px;font-weight: 600;color: var(--accent);display: fle"
    "x;align-items: center;gap: 6px;}.advanced-box {display: none;margin-top: 10px;padding: 12px;backgrou"
    "nd: #080c16;border: 1px solid #152238;border-radius: 10px;}/* 模态框与实时动画 */.modal-overlay {position: f"
    "ixed;top: 0; left: 0; right: 0; bottom: 0;background: rgba(6, 9, 19, 0.85);backdrop-filter: blur(8px"
    ");display: none;align-items: center;justify-content: center;z-index: 100;padding: 20px;}.modal-card "
    "{background: #0e1628;border: 1px solid var(--card-border);border-radius: 20px;width: 100%;max-width:"
    " 420px;padding: 28px 24px;text-align: center;box-shadow: 0 20px 50px rgba(0, 0, 0, 0.8);position: re"
    "lative;}.radar-container {width: 80px;height: 80px;margin: 0 auto 18px;position: relative;display: f"
    "lex;align-items: center;justify-content: center;}.radar-ring {position: absolute;width: 100%;height:"
    " 100%;border-radius: 50%;border: 2px solid var(--accent);animation: pulseRadar 1.8s cubic-bezier(0.2"
    "5, 1, 0.5, 1) infinite;}@keyframes pulseRadar {0% { transform: scale(0.6); opacity: 0.8; }100% { tra"
    "nsform: scale(1.4); opacity: 0; }}.radar-core {width: 48px;height: 48px;border-radius: 50%;backgroun"
    "d: linear-gradient(135deg, var(--accent), #0088ff);display: flex;align-items: center;justify-content"
    ": center;font-size: 22px;z-index: 2;box-shadow: 0 0 16px rgba(0, 240, 255, 0.4);}.modal-title {font-"
    "size: 17px;font-weight: 700;color: #fff;margin-bottom: 8px;}.modal-msg {font-size: 13px;color: var(-"
    "-muted);line-height: 1.5;margin-bottom: 20px;}.ip-card {background: #080d1a;border: 1px solid rgba(0"
    ", 255, 136, 0.35);border-radius: 12px;padding: 14px;margin-bottom: 18px;display: none;}.ip-card-labe"
    "l {font-size: 11px;color: var(--accent-sub);font-weight: 600;text-transform: uppercase;}.ip-card-val"
    " {font-size: 22px;font-weight: 700;color: #fff;font-family: ui-monospace, SFMono-Regular, Menlo, Mon"
    "aco, Consolas, monospace;margin: 4px 0;}.btn-dash {background: linear-gradient(135deg, var(--accent-"
    "sub), #00b359);color: #060913;font-weight: 700;display: none;}.btn-dash:hover {background: linear-gr"
    "adient(135deg, #33ff99, #00cc66);transform: translateY(-1px);}.compat-banner {background: rgba(255, "
    "183, 0, 0.1);border: 1px solid rgba(255, 183, 0, 0.35);border-radius: 12px;padding: 12px 14px;font-s"
    "ize: 12px;color: #ffd166;line-height: 1.5;margin-bottom: 18px;display: none;}.status-log {font-famil"
    "y: ui-monospace, SFMono-Regular, monospace;font-size: 11px;background: #060a14;border: 1px solid #16"
    "2238;border-radius: 8px;padding: 8px;color: #7990ac;text-align: left;max-height: 80px;overflow-y: au"
    "to;margin-bottom: 14px;}</style></head><body><div class=\"container\"><div class=\"top-badge\">⚡ Ope"
    "nVela Wireless Suite</div><div class=\"main-card\"><div class=\"title-row\"><h1><span>🌌</span> Phoen"
    "ix 蓝牙极速配网</h1><p>无需切换手机 Wi-Fi，网页一键直连设备蓝牙，快速下发网络凭证与大模型密钥</p></div><div class=\"mode-switch\"><div cla"
    "ss=\"mode-tab active\" id=\"tabBle\">⚡ 蓝牙极速配网</div><a href=\"setup.html\" class=\"mode-tab\" id=\"ta"
    "bAp\">📡 传统热点配网</a></div><div class=\"compat-banner\" id=\"compatBanner\">⚠️ <b>当前浏览器未检测到 Web Bluetoo"
    "th 支持：</b><br>推荐使用 <b>Chrome / Edge 浏览器</b> (PC/Mac/Android)。若在 iOS 设备，请通过支持 Web BLE 的专用浏览器访问，或点击上方切"
    "换为「📡 传统热点配网」。</div><div class=\"ble-status-box\" id=\"bleStatusBox\"><div style=\"display: flex; jus"
    "tify-content: space-between; align-items: center; width: 100%;\"><div class=\"ble-icon-circle\" id=\""
    "bleIcon\">⚡</div><div class=\"duplex-bar\" title=\"全双工链路指示灯 (发送/接收实时流光)\"><span>GATT链路:</span><span "
    "class=\"led-pill\" id=\"txLed\">TX</span><span class=\"led-pill\" id=\"rxLed\">RX</span></div></div>"
    "<div class=\"ble-title\" id=\"bleTitle\">未连接蓝牙设备</div><div class=\"ble-desc\" id=\"bleDesc\">请确保 Gem"
    "ini-S1 设备已通电且位于手机/电脑 5 米范围内</div><div class=\"sync-badge\" id=\"syncBadge\" style=\"display: none;\""
    ">✅ 已从硬件同步当前配置</div><button class=\"btn btn-ble\" id=\"btnConnectBle\" onclick=\"connectBluetooth()\""
    "><span>🔍</span> 搜索并配对 Phoenix 设备</button></div><div id=\"provForm\" style=\"opacity: 0.45; pointer-e"
    "vents: none; transition: 0.3s ease;\"><div class=\"form-group\"><div class=\"form-label\"><span>Wi-F"
    "i 网络名称 (SSID) <span class=\"req\">*</span></span><button class=\"scan-btn\" type=\"button\" onclick="
    "\"requestWifiScan()\" style=\"background: none; border: none; color: var(--accent); cursor: pointer;"
    " font-size: 11px;\">🔄 重新扫描</button></div><div class=\"input-wrap\"><select id=\"wifiSelect\" onchang"
    "e=\"onSsidSelectChange()\"><option value=\"\">-- 请选择或手动输入下方 Wi-Fi --</option></select></div><input t"
    "ype=\"text\" id=\"customSsid\" placeholder=\"手动输入 Wi-Fi 名称 (支持 2.4GHz)\" style=\"margin-top: 6px;\">"
    "</div><div class=\"form-group\"><div class=\"form-label\"><span>Wi-Fi 密码 (PSK)</span><span style=\"f"
    "ont-size: 11px; cursor: pointer; color: var(--muted);\" onclick=\"togglePwdVisibility()\">👁️ 查看/隐藏</"
    "span></div><input type=\"password\" id=\"wifiPwd\" placeholder=\"请输入 Wi-Fi 密码 (无密码请留空)\"></div><div "
    "class=\"advanced-toggle\" onclick=\"toggleAdvanced()\"><span>⚙️ 智能体高级配置 (DeepSeek API Key / Prompt)<"
    "/span><span id=\"advArrow\">▼</span></div><div class=\"advanced-box\" id=\"advBox\"><div class=\"for"
    "m-group\" style=\"margin-top: 0;\"><div class=\"form-label\">DeepSeek API Key</div><input type=\"pas"
    "sword\" id=\"apiKey\" placeholder=\"sk-...\"></div><div class=\"form-group\"><div class=\"form-label"
    "\">模型选择</div><select id=\"modelSelect\"><option value=\"deepseek-chat\">deepseek-chat (V3 通用)</optio"
    "n><option value=\"deepseek-reasoner\">deepseek-reasoner (R1 深度思考)</option></select></div><div class="
    "\"form-group\"><div class=\"form-label\">具身人设 Prompt</div><textarea id=\"agentPrompt\" rows=\"3\" pl"
    "aceholder=\"例如：你是一只生活在桌面全息屏里的赛博凤凰，机敏、幽默、热爱技术...\"></textarea></div></div><button class=\"btn btn-sub"
    "mit\" id=\"btnSubmit\" onclick=\"sendConfigAndConnect()\">🚀 一键写入配置并连网</button><div style=\"display: "
    "flex; gap: 8px; margin-top: 10px;\"><button class=\"btn\" type=\"button\" id=\"btnSaveParams\" oncli"
    "ck=\"sendAgentConfigOnly()\" style=\"flex: 1; background: #121e36; border: 1px solid rgba(0, 240, 25"
    "5, 0.4); color: var(--accent); font-size: 12px; font-weight: 600; padding: 10px; cursor: pointer;\">"
    "💾 仅保存智能体参数</button><button class=\"btn\" type=\"button\" id=\"btnRefreshConfig\" onclick=\"requestDe"
    "viceConfig()\" style=\"width: 105px; background: #0c1425; border: 1px solid #1c2b45; color: var(--mu"
    "ted); font-size: 11px; padding: 10px; cursor: pointer;\">🔄 回读配置</button></div></div></div></div><div"
    " class=\"modal-overlay\" id=\"modalOverlay\"><div class=\"modal-card\"><div class=\"radar-container\""
    "><div class=\"radar-ring\" id=\"radarRing\"></div><div class=\"radar-core\" id=\"radarIcon\">📡</div>"
    "</div><div class=\"modal-title\" id=\"modalTitle\">正在建立无线连接...</div><div class=\"modal-msg\" id=\"mo"
    "dalMsg\">已通过蓝牙下发 Wi-Fi 凭证，设备正在关联路由器并向 DHCP 获取 IP 地址...<br>请稍候，设备屏幕也将实时同步连网动效。</div><div class=\"stat"
    "us-log\" id=\"statusLog\">[SYS] 正在等待板端 GATT Notify 响应...</div><div class=\"ip-card\" id=\"ipCard\"><"
    "div class=\"ip-card-label\">🎉 设备已成功连入局域网</div><div class=\"ip-card-val\" id=\"ipVal\">192.168.x.x</d"
    "iv><div style=\"font-size: 11px; color: var(--muted);\">微胶囊已同步激活，点击下方直达伴侣管理看板</div></div><a href=\"#"
    "\" class=\"btn btn-dash\" id=\"btnGoDashboard\" target=\"_blank\">🚀 立即进入极客伴侣看板</a><button class=\"bt"
    "n\" id=\"btnCloseModal\" onclick=\"closeModal()\" style=\"margin-top: 10px; background: #162238; col"
    "or: var(--muted); font-size: 12px; display: none;\">返回配网界面</button></div></div><script>/* BLE UUID 常"
    "量定义 */const SERVICE_UUID = '0000ffe0-0000-1000-8000-00805f9b34fb';const CHAR_WRITE_UUID = '0000ffe1-"
    "0000-1000-8000-00805f9b34fb';const CHAR_NOTIFY_UUID = '0000ffe2-0000-1000-8000-00805f9b34fb';const C"
    "HAR_INFO_UUID = '0000ffe3-0000-1000-8000-00805f9b34fb';let bleDevice = null;let bleServer = null;let"
    " writeChar = null;let notifyChar = null;let currentTargetIp = '';window.addEventListener('DOMContent"
    "Loaded', () => {if (!navigator.bluetooth) {document.getElementById('compatBanner').style.display = '"
    "block';document.getElementById('btnConnectBle').disabled = true;}});function flashTx() {const el = d"
    "ocument.getElementById('txLed');if (el) {el.classList.add('active-tx');setTimeout(() => el.classList"
    ".remove('active-tx'), 180);}}function flashRx() {const el = document.getElementById('rxLed');if (el)"
    " {el.classList.add('active-rx');setTimeout(() => el.classList.remove('active-rx'), 180);}}function l"
    "ogMsg(msg) {const el = document.getElementById('statusLog');if (el) {const time = new Date().toLocal"
    "eTimeString();el.innerHTML += `<div>[${time}] ${msg}</div>`;el.scrollTop = el.scrollHeight;}}async f"
    "unction connectBluetooth() {try {logMsg(\"正在调起系统蓝牙扫描框...\");bleDevice = await navigator.bluetooth.re"
    "questDevice({filters: [{ namePrefix: 'Phoenix' },{ namePrefix: 'OpenVela' }],optionalServices: [SERV"
    "ICE_UUID]});bleDevice.addEventListener('gattserverdisconnected', onDisconnected);document.getElement"
    "ById('bleTitle').innerText = '正在建立 GATT 连接...';logMsg(`正在连接设备: ${bleDevice.name}`);bleServer = await"
    " bleDevice.gatt.connect();logMsg(\"GATT Server 连接成功，正在解析服务...\");const service = await bleServer.get"
    "PrimaryService(SERVICE_UUID);/* 获取特征值 */writeChar = await service.getCharacteristic(CHAR_WRITE_UUID)"
    ";notifyChar = await service.getCharacteristic(CHAR_NOTIFY_UUID);/* 尝试读取硬件固件信息 */try {const infoChar "
    "= await service.getCharacteristic(CHAR_INFO_UUID);const infoVal = await infoChar.readValue();const d"
    "evInfo = new TextDecoder().decode(infoVal);logMsg(`设备信息: ${devInfo}`);} catch (e) {}/* 开启 Notify 监听 "
    "*/await notifyChar.startNotifications();notifyChar.addEventListener('characteristicvaluechanged', on"
    "NotifyReceived);/* 更新 UI 状态 */document.getElementById('bleStatusBox').classList.add('connected');doc"
    "ument.getElementById('bleIcon').innerText = '✅';document.getElementById('bleTitle').innerText = `已连接"
    ": ${bleDevice.name}`;document.getElementById('bleDesc').innerText = '全双工 BLE 链路稳定就绪，支持双向参数回读、修改与配网';"
    "document.getElementById('btnConnectBle').style.display = 'none';/* 解锁配网表单 */const form = document.ge"
    "tElementById('provForm');form.style.opacity = '1';form.style.pointerEvents = 'auto';/* 双向全双工自动握手：自动回"
    "读板端当前配置 */await requestDeviceConfig();/* 自动触发一次周围 Wi-Fi 扫描 */await requestWifiScan();} catch (err) {"
    "console.error(\"蓝牙连接错误:\", err);logMsg(`蓝牙连接失败: ${err.message || err}`);document.getElementById('ble"
    "Title').innerText = '未连接蓝牙设备';alert('未连接蓝牙设备: ' + (err.message || '用户取消或连接失败'));}}function onDisconn"
    "ected() {logMsg(\"⚠️ 蓝牙连接已断开\");document.getElementById('bleStatusBox').classList.remove('connected'"
    ");document.getElementById('bleIcon').innerText = '⚡';document.getElementById('bleTitle').innerText ="
    " '蓝牙连接已断开';document.getElementById('bleDesc').innerText = '设备已断开连接，请重新搜索并配对';document.getElementById"
    "('btnConnectBle').style.display = 'inline-flex';document.getElementById('provForm').style.opacity = "
    "'0.45';document.getElementById('provForm').style.pointerEvents = 'none';const badge = document.getEl"
    "ementById('syncBadge');if (badge) badge.style.display = 'none';}/* 双向交互：请求板端回读配置 */async function re"
    "questDeviceConfig() {if (!writeChar) return;try {flashTx();logMsg(\"🔄 [TX] 正在请求板端回读当前配置 (get_config)"
    "...\");const payload = JSON.stringify({ cmd: \"get_config\" });await writeChar.writeValue(new TextEn"
    "coder().encode(payload));} catch (e) {logMsg(`[TX] 回读配置失败: ${e.message}`);}}/* 触发板端 Wi-Fi 扫描 */async"
    " function requestWifiScan() {if (!writeChar) return;try {flashTx();logMsg(\"📡 [TX] 正在请求板端扫描周围 Wi-Fi "
    "(scan)...\");const payload = JSON.stringify({ cmd: \"scan\" });await writeChar.writeValue(new TextEn"
    "coder().encode(payload));} catch (e) {logMsg(`[TX] 扫描请求下发失败: ${e.message}`);}}/* 双向交互：仅更新智能体参数 (无需重连"
    " Wi-Fi) */async function sendAgentConfigOnly() {if (!writeChar) {alert('蓝牙未连接，请先连接设备！');return;}cons"
    "t apiKey = document.getElementById('apiKey').value.trim();const model = document.getElementById('mod"
    "elSelect').value;const prompt = document.getElementById('agentPrompt').value.trim();const payload = "
    "{cmd: \"set_config\",agent: {api_key: apiKey,model: model,prompt: prompt}};try {flashTx();logMsg(\"💾"
    " [TX] 正在下发智能体参数更新 (set_config)...\");await writeChar.writeValue(new TextEncoder().encode(JSON.string"
    "ify(payload)));logMsg(\"配置下发完毕，正在等待板端 ACK 确认...\");} catch (e) {logMsg(`[TX] 下发失败: ${e.message}`);al"
    "ert(\"下发配置失败: \" + e.message);}}/* 处理板端主动通知数据 (全双工上行监听) */function onNotifyReceived(event) {flashRx("
    ");const value = event.target.value;const text = new TextDecoder().decode(value);console.log(\"[Notif"
    "y Recv]:\", text);try {const data = JSON.parse(text);if (data.event === 'scan_result') {handleScanRe"
    "sult(data);} else if (data.event === 'net_status') {handleNetStatus(data);} else if (data.event === "
    "'config_data') {handleConfigData(data);} else if (data.event === 'config_saved') {handleConfigSaved("
    "data);} else if (data.event === 'system_info') {logMsg(`📥 [RX:系统遥测] 平台=${data.soc}, OS=${data.os}, 固"
    "件=${data.fw_ver}`);}} catch (e) {logMsg(`数据解析异常: ${text}`);}}function handleConfigData(data) {logMsg"
    "(\"📥 [RX] 收到板端配置回读数据 (config_data)\");if (data.wifi && data.wifi.ssid) {document.getElementById('cus"
    "tomSsid').value = data.wifi.ssid;if (data.wifi.connected) {logMsg(`设备当前已连入 Wi-Fi: ${data.wifi.ssid} "
    "(IP: ${data.wifi.ip || '已连接'})`);}}if (data.agent) {if (data.agent.model) {document.getElementById('"
    "modelSelect').value = data.agent.model;}if (data.agent.prompt) {document.getElementById('agentPrompt"
    "').value = data.agent.prompt;}if (data.agent.api_key_set) {const keyInput = document.getElementById("
    "'apiKey');keyInput.placeholder = `已保存: ${data.agent.api_key_masked} (如需修改请输入新Key)`;}}const badge = d"
    "ocument.getElementById('syncBadge');if (badge) {badge.style.display = 'inline-flex';const keyDesc = "
    "data.agent?.api_key_set ? 'API Key 已配置' : 'API Key 未配置';badge.innerHTML = `✅ 已同步硬件配置: 模型 [${data.age"
    "nt?.model || 'deepseek-chat'}], ${keyDesc}`;}}function handleConfigSaved(data) {logMsg(`🎉 [RX] ${dat"
    "a.msg || '智能体参数已成功保存并持久化'}`);alert(`🎉 ${data.msg || '智能体参数已成功在板端更新并持久化！'}`);requestDeviceConfig();}f"
    "unction handleScanResult(data) {const aps = data.aps || [];const sel = document.getElementById('wifi"
    "Select');sel.innerHTML = '<option value=\"\">-- 选择扫描到的热点 (' + aps.length + '个) --</option>';aps.forE"
    "ach(ap => {const opt = document.createElement('option');opt.value = ap.ssid;opt.innerText = `${ap.ss"
    "id} (${ap.rssi} dBm | ${ap.auth})`;sel.appendChild(opt);});logMsg(`📥 [RX] 已获取周围 Wi-Fi 列表 (共 ${aps.le"
    "ngth} 个)`);}function onSsidSelectChange() {const sel = document.getElementById('wifiSelect');if (sel"
    ".value) {document.getElementById('customSsid').value = sel.value;}}/* 下发配网凭证并启动连网 */async function s"
    "endConfigAndConnect() {const ssid = document.getElementById('customSsid').value.trim();const psk = d"
    "ocument.getElementById('wifiPwd').value;const apiKey = document.getElementById('apiKey').value.trim("
    ");const model = document.getElementById('modelSelect').value;const prompt = document.getElementById("
    "'agentPrompt').value.trim();if (!ssid) {alert('请输入或选择 Wi-Fi 名称！');return;}if (!writeChar) {alert('蓝牙"
    "未连接，请先连接设备！');return;}/* 显示连网全屏模态框 */showModal(\"📡 正在尝试加入 Wi-Fi...\", `正在向设备下发网络凭证并加入 <b>${ssid}</b>"
    "。<br>请留意板端屏幕上方金色连网动画...`);const configPayload = {cmd: \"config\",wifi: { ssid: ssid, psk: psk },agen"
    "t: {api_key: apiKey,model: model,prompt: prompt}};try {flashTx();logMsg(`🚀 [TX] 正在通过 BLE 下发配网凭证 (${s"
    "sid})...`);const data = new TextEncoder().encode(JSON.stringify(configPayload));await writeChar.writ"
    "eValue(data);logMsg(\"凭证下发完毕，正在等待板端网络事件...\");} catch (e) {logMsg(`[TX] 下发失败: ${e.message}`);alert(\""
    "下发配置失败: \" + e.message);}}function isValidStaIp(ip) {if (!ip || ip === '0.0.0.0' || ip === '127.0.0."
    "1') return false;if (ip.startsWith('192.168.4.')) return false;if (ip === '10.0.0.2' || ip === '10.0"
    ".0.1' || ip === '10.0.2.15') return false;if (ip.startsWith('169.254.')) return false;return true;}f"
    "unction handleNetStatus(data) {logMsg(`设备状态上报: state=${data.state}, ip=${data.ip}, msg=${data.msg}`)"
    ";if (data.state === 'connected' && isValidStaIp(data.ip)) {currentTargetIp = data.ip;document.getEle"
    "mentById('radarRing').style.animation = 'none';document.getElementById('radarRing').style.borderColo"
    "r = 'var(--accent-sub)';document.getElementById('radarIcon').innerText = '🎉';document.getElementById"
    "('modalTitle').innerText = '🎉 Wi-Fi 连接成功！';document.getElementById('modalMsg').innerHTML =`设备已成功连接至 "
    "<b>${data.ssid}</b>！<br>局域网 IP 地址已分配完毕，无需重启即可无缝管理。`;document.getElementById('ipVal').innerText = dat"
    "a.ip;document.getElementById('ipCard').style.display = 'block';const dashUrl = data.dashboard_url ||"
    " `http://${data.ip}:8080/`;const btnDash = document.getElementById('btnGoDashboard');btnDash.href = "
    "dashUrl;btnDash.style.display = 'inline-flex';document.getElementById('btnCloseModal').style.display"
    " = 'inline-flex';/* 倒计时自动跳转 */let countdown = 3;btnDash.innerText = `🚀 立即进入极客伴侣看板 (${countdown}s)`;c"
    "onst timer = setInterval(() => {countdown--;if (countdown > 0) {btnDash.innerText = `🚀 立即进入极客伴侣看板 ($"
    "{countdown}s)`;} else {clearInterval(timer);btnDash.innerText = `🚀 正在跳转至 ${data.ip}...`;window.locat"
    "ion.href = dashUrl;}}, 1000);} else if (data.state === 'connecting') {document.getElementById('modal"
    "Title').innerText = '正在握手连网...';document.getElementById('modalMsg').innerText = data.msg || '正在向路由器发"
    "起关联握手并申请 DHCP IP...';}}function showModal(title, msg) {document.getElementById('modalTitle').innerHT"
    "ML = title;document.getElementById('modalMsg').innerHTML = msg;document.getElementById('modalOverlay"
    "').style.display = 'flex';document.getElementById('ipCard').style.display = 'none';document.getEleme"
    "ntById('btnGoDashboard').style.display = 'none';document.getElementById('btnCloseModal').style.displ"
    "ay = 'none';}function closeModal() {document.getElementById('modalOverlay').style.display = 'none';}"
    "function toggleAdvanced() {const box = document.getElementById('advBox');const arrow = document.getE"
    "lementById('advArrow');if (box.style.display === 'block') {box.style.display = 'none';arrow.innerTex"
    "t = '▼';} else {box.style.display = 'block';arrow.innerText = '▲';}}function togglePwdVisibility() {"
    "const input = document.getElementById('wifiPwd');input.type = (input.type === 'password') ? 'text' :"
    " 'password';}</script></body></html>";

static const char s_dashboard_html[] =
    "<!DOCTYPE html><html lang=\"zh-CN\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\""
    "width=device-width, initial-scale=1.0\"><title>Phoenix HoloDesk-S1 Geek Dashboard</title><style>:roo"
    "t {--bg: #080c14;--card: #101726;--border: #1c2a44;--accent: #00e5ff;--accent-sub: #00ff88;--text: #"
    "e6edf3;--muted: #8b9eb5;}body {margin: 0;padding: 24px;background: var(--bg);color: var(--text);font"
    "-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, sans-serif;}.wrap {max-width: 960p"
    "x;margin: 0 auto;}header {display: flex;justify-content: space-between;align-items: center;margin-bo"
    "ttom: 20px;border-bottom: 1px solid var(--border);padding-bottom: 14px;}h1 {color: var(--accent);fon"
    "t-size: 20px;margin: 0;display: flex;align-items: center;gap: 8px;font-weight: 700;}.badge {backgrou"
    "nd: #182842;border: 1px solid #233b63;color: var(--accent);padding: 4px 12px;border-radius: 20px;fon"
    "t-size: 12px;font-weight: 600;}.selector {display: flex;gap: 10px;margin-bottom: 20px;overflow-x: au"
    "to;padding-bottom: 4px;}.pill-btn {background: var(--card);border: 1px solid var(--border);color: va"
    "r(--text);padding: 10px 16px;border-radius: 24px;cursor: pointer;font-size: 13px;font-weight: 600;di"
    "splay: flex;align-items: center;gap: 6px;transition: 0.2s;white-space: nowrap;}.pill-btn:hover {bord"
    "er-color: var(--accent);color: var(--accent);}.pill-btn.active {background: linear-gradient(135deg, "
    "rgba(0, 229, 255, 0.15), rgba(0, 255, 136, 0.15));border-color: var(--accent);color: #fff;box-shadow"
    ": 0 0 16px rgba(0, 229, 255, 0.25);}.grid {display: grid;grid-template-columns: repeat(auto-fit, min"
    "max(280px, 1fr));gap: 16px;margin-bottom: 20px;}.card {background: var(--card);border: 1px solid var"
    "(--border);border-radius: 14px;padding: 18px;box-shadow: 0 8px 24px rgba(0, 0, 0, 0.4);position: rel"
    "ative;overflow: hidden;}.card::before {content: '';position: absolute;top: 0;left: 0;right: 0;height"
    ": 2px;background: linear-gradient(90deg, transparent, var(--border), transparent);}.card.highlight::"
    "before {background: linear-gradient(90deg, var(--accent), var(--accent-sub));}.card-head {display: f"
    "lex;justify-content: space-between;align-items: center;margin-bottom: 12px;}.card-title {font-size: "
    "15px;font-weight: bold;color: var(--accent);display: flex;align-items: center;gap: 6px;}.metric-row "
    "{display: flex;gap: 12px;margin-bottom: 14px;}.m-block {background: #0a0f1c;padding: 10px;border-rad"
    "ius: 8px;flex: 1;text-align: center;border: 1px solid rgba(255, 255, 255, 0.04);}.m-lbl {font-size: "
    "11px;color: var(--muted);}.m-val {font-size: 20px;font-weight: bold;color: var(--accent-sub);margin-"
    "top: 4px;}input, button {width: 100%;box-sizing: border-box;padding: 10px;border-radius: 8px;border:"
    " 1px solid var(--border);background: #090d16;color: #fff;font-size: 13px;}button {background: var(--"
    "accent);color: #04060a;border: none;font-weight: bold;cursor: pointer;margin-top: 10px;transition: 0"
    ".2s;}button:hover {background: #33ebff;transform: translateY(-1px);}.btn-secondary {background: #182"
    "842;color: #9bc0e7;border: 1px solid #233b63;}.btn-secondary:hover {background: #22375a;color: #fff;"
    "}.btn-warn {background: #d29922;color: #000;}.btn-warn:hover {background: #ebb034;}.memo-item {backg"
    "round: #0a0f1c;padding: 8px 12px;border-radius: 6px;font-size: 12px;margin-bottom: 6px;color: #c0d2e"
    "8;border-left: 2px solid var(--accent);}.terminal-window {background: #05080f;border: 1px solid #1c2"
    "a44;border-radius: 8px;font-family: ui-monospace, \"SF Mono\", \"Cascadia Code\", \"JetBrains Mono\""
    ", Menlo, Consolas, monospace;font-size: 11.5px;line-height: 1.5;color: #c9d1d9;height: 320px;overflo"
    "w-y: auto;padding: 10px 14px;white-space: pre-wrap;word-break: break-all;box-shadow: inset 0 2px 10p"
    "x rgba(0, 0, 0, 0.6);}.log-line {display: block;padding: 1px 0;transition: background 0.15s;}.log-li"
    "ne:hover {background: rgba(255, 255, 255, 0.05);}.log-lvl-E { color: #ff5555; font-weight: 600; }.lo"
    "g-lvl-W { color: #f1fa8c; }.log-lvl-I { color: #50fa7b; }.log-lvl-D { color: #8be9fd; }.log-lvl-V { "
    "color: #bd93f9; }</style></head><body><div class=\"wrap\"><header><h1>💎 Phoenix HoloDesk-S1 极客伴侣看板</"
    "h1><div class=\"badge\" id=\"connStatus\">● 局域网已连接</div></header><div class=\"selector\"><div class="
    "\"pill-btn\" id=\"tab-familiar\" onclick=\"switchCartridge('familiar')\">🐱 桌面使魔</div><div class=\"pi"
    "ll-btn\" id=\"tab-memo\" onclick=\"switchCartridge('memo')\">💡 灵感外脑</div><div class=\"pill-btn\" id="
    "\"tab-clock\" onclick=\"switchCartridge('clock')\">⏰ 翻页时钟</div><div class=\"pill-btn\" id=\"tab-zen\""
    " onclick=\"switchCartridge('zen')\">🪷 赛博木鱼</div></div><div class=\"grid\"><div class=\"card\" id=\"c"
    "ard-familiar\"><div class=\"card-head\"><div class=\"card-title\">🐱 桌面使魔萌宠</div><span class=\"badge\""
    " id=\"moodTag\">陪伴中</span></div><div class=\"metric-row\"><div class=\"m-block\"><div class=\"m-lbl\""
    ">使魔亲密度</div><div class=\"m-val\" id=\"affinityVal\">--</div></div><div class=\"m-block\"><div class="
    "\"m-lbl\">元气饱腹度</div><div class=\"m-val\">95%</div></div></div><button class=\"btn-secondary\" oncli"
    "ck=\"doAction('pet')\">🐾 远程轻抚使魔撒娇</button></div><div class=\"card\" id=\"card-memo\"><div class=\"ca"
    "rd-head\"><div class=\"card-title\">💡 灵感外脑速记</div><span class=\"badge\" id=\"memoCountTag\">3 条</spa"
    "n></div><div class=\"memo-item\" id=\"lastMemo\">正在同步端侧备忘...</div><input id=\"memoInput\" type=\"tex"
    "t\" placeholder=\"在此输入闪念，即刻存入端侧外脑\"><button onclick=\"addMemo()\">💡 推入灵感外脑</button></div><div class="
    "\"card\" id=\"card-clock\"><div class=\"card-head\"><div class=\"card-title\">⏰ 翻页时钟 & 专注流</div><spa"
    "n class=\"badge\" id=\"pomoStatusTag\">待命</span></div><div class=\"metric-row\"><div class=\"m-block"
    "\"><div class=\"m-lbl\">专注倒计时</div><div class=\"m-val\" id=\"pomoRemain\">--:--</div></div><div clas"
    "s=\"m-block\"><div class=\"m-lbl\">推理延迟</div><div class=\"m-val\" id=\"latencyVal\">-- ms</div></div"
    "></div><button class=\"btn-secondary\" onclick=\"doAction('pomo_toggle')\">🍅 开启 / 暂停番茄专注</button></d"
    "iv><div class=\"card\" id=\"card-zen\"><div class=\"card-head\"><div class=\"card-title\">🪷 极客禅意木鱼</"
    "div><span class=\"badge\">消除焦虑</span></div><div class=\"metric-row\"><div class=\"m-block\"><div cla"
    "ss=\"m-lbl\">累计功德数</div><div class=\"m-val\" id=\"meritVal\">--</div></div><div class=\"m-block\"><d"
    "iv class=\"m-lbl\">消耗 Tokens</div><div class=\"m-val\" id=\"tokensVal\">--</div></div></div><button "
    "onclick=\"doAction('knock_fish')\">🪷 敲击木鱼 (功德+1)</button></div></div><div class=\"card\" style=\"mar"
    "gin-bottom:20px;\"><div class=\"card-head\"><div class=\"card-title\">⚙️ 云端大模型与 Agent 配置中心</div><spa"
    "n class=\"badge\" id=\"cfgStatusBadge\">端侧热加载</span></div><div style=\"display:grid; grid-template-c"
    "olumns:repeat(auto-fit,minmax(260px,1fr)); gap:12px; margin-bottom:10px;\"><div><div style=\"font-si"
    "ze:12px; color:var(--muted); margin-bottom:4px; font-weight:600;\">大模型 API Key:</div><input id=\"api"
    "Key\" type=\"password\" placeholder=\"输入云端 API Key (如 sk-xxxx)\"></div><div><div style=\"font-size:1"
    "2px; color:var(--muted); margin-bottom:4px; font-weight:600;\">大模型名称 (Model):</div><input id=\"model"
    "Name\" type=\"text\" placeholder=\"如 deepseek-chat 或 gpt-4o-mini\"></div></div><div style=\"font-siz"
    "e:12px; color:var(--muted); margin-bottom:4px; font-weight:600;\">Agent 系统人设提示词 (Prompt):</div><text"
    "area id=\"agentPrompt\" rows=\"2\" style=\"width:100%; box-sizing:border-box; padding:10px; border-r"
    "adius:8px; border:1px solid var(--border); background:#090d16; color:#fff; font-size:13px; resize:no"
    "ne;\" placeholder=\"如：你是一个贴心的赛博桌面极客助手，语气温和简短\"></textarea><div style=\"display:flex; gap:10px; margi"
    "n-top:12px;\"><button onclick=\"saveAgentConfig()\">💾 保存并热加载至开发板</button><button class=\"btn-warn\" "
    "onclick=\"resetWifi()\">📡 重置 Wi-Fi 并返回热点</button></div></div><div class=\"card\" id=\"card-storage\""
    "><div class=\"card-head\"><div class=\"card-title\">📁 外置 MicroSD / TF 卡存储管理</div><span class=\"badge"
    "\" id=\"sdcardMountBadge\">探测中...</span></div><div style=\"background:#090d16; border:1px solid var("
    "--border); border-radius:10px; padding:12px; margin-bottom:16px;\"><div style=\"display:flex; justif"
    "y-content:space-between; font-size:12px; margin-bottom:8px;\"><span style=\"color:var(--muted)\">挂载目"
    "录: <b id=\"sdcardMountPoint\" style=\"color:var(--accent)\">/mnt/sdcard</b></span><span style=\"colo"
    "r:var(--muted)\">已用: <b id=\"sdcardUsedPct\" style=\"color:var(--accent-sub)\">--%</b> (<span id=\"s"
    "dcardUsedMb\">0</span> MB / <span id=\"sdcardTotalMb\">0</span> MB)</span></div><div style=\"height:"
    "8px; background:#141c2c; border-radius:4px; overflow:hidden;\"><div id=\"sdcardProgressBar\" style=\""
    "width:0%; height:100%; background:linear-gradient(90deg, var(--accent), var(--accent-sub)); transiti"
    "on:width 0.4s ease;\"></div></div><div style=\"display:flex; gap:12px; margin-top:10px; font-size:11"
    "px; color:var(--muted);\"><span>📌 持久配置: <code id=\"dataBaseDir\" style=\"color:#9bc0e7\">/data/phoen"
    "ix</code></span><span>⚡ 中间分片: <code id=\"tempBaseDir\" style=\"color:#9bc0e7\">/tmp/phoenix</code></"
    "span></div></div><div style=\"display:flex; justify-content:space-between; align-items:center; flex-"
    "wrap:wrap; gap:8px; margin-bottom:12px;\"><div style=\"display:flex; align-items:center; gap:6px;\">"
    "<span style=\"font-size:12px; color:var(--muted)\">路径:</span><code id=\"currentPathDisplay\" style=\""
    "background:#182842; color:var(--accent); padding:4px 8px; border-radius:6px; font-size:12px; font-we"
    "ight:bold;\">/</code><button class=\"btn-secondary\" style=\"margin:0; padding:4px 10px; font-size:1"
    "1px; width:auto;\" onclick=\"sdcardGoUp()\">⬆️ 上一级</button><button class=\"btn-secondary\" style=\"m"
    "argin:0; padding:4px 10px; font-size:11px; width:auto;\" onclick=\"sdcardRefreshList()\">🔄 刷新</butto"
    "n></div><div style=\"display:flex; gap:6px;\"><button class=\"btn-secondary\" style=\"margin:0; padd"
    "ing:4px 10px; font-size:11px; width:auto;\" onclick=\"sdcardGoPath('/sounds')\">🎵 sounds</button><bu"
    "tton class=\"btn-secondary\" style=\"margin:0; padding:4px 10px; font-size:11px; width:auto;\" oncli"
    "ck=\"sdcardGoPath('/logs')\">📜 logs</button><button class=\"btn-secondary\" style=\"margin:0; paddin"
    "g:4px 10px; font-size:11px; width:auto;\" onclick=\"sdcardGoPath('/docs')\">📑 docs</button></div></d"
    "iv><div style=\"background:#090d16; border:1px solid var(--border); border-radius:8px; max-height:26"
    "0px; overflow-y:auto; margin-bottom:16px;\"><table style=\"width:100%; border-collapse:collapse; fon"
    "t-size:12px; text-align:left;\"><thead><tr style=\"border-bottom:1px solid var(--border); color:var("
    "--muted);\"><th style=\"padding:8px 12px;\">名称</th><th style=\"padding:8px 12px; width:80px;\">大小</t"
    "h><th style=\"padding:8px 12px; width:120px; text-align:right;\">操作</th></tr></thead><tbody id=\"sdc"
    "ardFileList\"><tr><td colspan=\"3\" style=\"padding:16px; text-align:center; color:var(--muted)\">正在"
    "读取 TF 卡文件系统...</td></tr></tbody></table></div><div style=\"display:grid; grid-template-columns:repea"
    "t(auto-fit,minmax(280px,1fr)); gap:12px;\"><div style=\"background:#0a0f1c; padding:12px; border-rad"
    "ius:8px; border:1px solid rgba(255,255,255,0.04);\"><div style=\"font-size:12px; color:var(--accent)"
    "; font-weight:600; margin-bottom:6px;\">📁 新建子目录</div><div style=\"display:flex; gap:8px;\"><input id"
    "=\"newDirName\" type=\"text\" placeholder=\"目录名称 (如 music)\" style=\"padding:8px; font-size:12px;\">"
    "<button style=\"margin:0; width:auto; padding:8px 14px; font-size:12px; white-space:nowrap;\" onclic"
    "k=\"sdcardMkdir()\">新建</button></div></div><div style=\"background:#0a0f1c; padding:12px; border-rad"
    "ius:8px; border:1px solid rgba(255,255,255,0.04);\"><div style=\"font-size:12px; color:var(--accent-"
    "sub); font-weight:600; margin-bottom:6px;\">✍️ 写入文件 / 上传文本</div><input id=\"uploadFileName\" type=\""
    "text\" placeholder=\"文件名 (如 memo.txt)\" style=\"padding:8px; font-size:12px; margin-bottom:6px;\"><t"
    "extarea id=\"uploadFileContent\" rows=\"2\" placeholder=\"文件内容 (纯文本、脚本或配置)\" style=\"width:100%; box"
    "-sizing:border-box; padding:8px; border-radius:8px; border:1px solid var(--border); background:#090d"
    "16; color:#fff; font-size:12px; resize:none;\"></textarea><div style=\"display:flex; gap:8px; margin"
    "-top:6px;\"><input type=\"file\" id=\"localFileInput\" style=\"display:none;\" onchange=\"handleLoca"
    "lFileSelected(this)\"><button class=\"btn-secondary\" style=\"margin:0; padding:6px 12px; font-size:"
    "11px; width:auto;\" onclick=\"document.getElementById('localFileInput').click()\">📂 选择本地文件</button><"
    "button style=\"margin:0; padding:6px 12px; font-size:11px; flex:1;\" onclick=\"sdcardUploadText()\">"
    "🚀 保存并写入 TF 卡</button></div></div></div></div><div class=\"card\" id=\"card-logs\" style=\"margin-bot"
    "tom:20px;\"><div class=\"card-head\"><div class=\"card-title\">📜 实时系统日志终端 (Live Kernel & App Logs)</"
    "div><div style=\"display:flex; align-items:center; gap:8px;\"><span class=\"badge\" id=\"logStreamBa"
    "dge\">● 实时监听中</span><span style=\"font-size:11px; color:var(--muted)\" id=\"logCursorTag\">Cursor: 0"
    " B</span></div></div><div style=\"display:flex; justify-content:space-between; align-items:center; f"
    "lex-wrap:wrap; gap:8px; margin-bottom:10px;\"><div style=\"display:flex; align-items:center; gap:6px"
    "; flex:1; min-width:280px;\"><select id=\"logLevelSelect\" onchange=\"changeLogLevel(this.value)\" s"
    "tyle=\"width:auto; padding:6px 10px; font-size:12px; border-radius:6px; background:#090d16; color:#f"
    "ff; border:1px solid var(--border);\"><option value=\"all\">🔍 显示过滤: 全部级别</option><option value=\"INF"
    "O\">🟢 仅 INFO 及以上</option><option value=\"WARN\">🟡 仅 WARN 及以上</option><option value=\"ERROR\">🔴 仅 ERR"
    "OR 错误</option><option value=\"DEBUG\">🔵 DEBUG 及以上</option></select><input id=\"logFilterInput\" type"
    "=\"text\" placeholder=\"关键词实时过滤...\" oninput=\"applyLogFilter()\" style=\"padding:6px 10px; font-siz"
    "e:12px; margin:0; flex:1; min-width:140px;\"></div><div style=\"display:flex; gap:6px; flex-wrap:wra"
    "p;\"><button class=\"btn-secondary\" id=\"autoScrollBtn\" style=\"margin:0; padding:6px 10px; font-s"
    "ize:11px; width:auto;\" onclick=\"toggleAutoScroll()\">⏬ 滚屏: 开</button><button class=\"btn-secondary"
    "\" id=\"pauseLogBtn\" style=\"margin:0; padding:6px 10px; font-size:11px; width:auto;\" onclick=\"to"
    "ggleLogPause()\">⏸️ 暂停</button><button class=\"btn-secondary\" style=\"margin:0; padding:6px 10px; f"
    "ont-size:11px; width:auto;\" onclick=\"clearLocalLogs()\">🧹 清屏</button><button class=\"btn-warn\" st"
    "yle=\"margin:0; padding:6px 10px; font-size:11px; width:auto;\" onclick=\"clearDeviceLogs()\">🗑️ 清空端"
    "侧缓存</button><button class=\"btn-secondary\" style=\"margin:0; padding:6px 10px; font-size:11px; widt"
    "h:auto;\" onclick=\"exportLogs()\">💾 导出日志</button></div></div><div class=\"terminal-window\" id=\"te"
    "rminalWindow\"><div class=\"log-line\" style=\"color:var(--muted)\">[SYSTEM] 连接到 Phoenix HoloDesk-S1"
    " 实时日志流 (增量游标就绪)...</div></div></div></div><script>let curCard = 'familiar';function refresh() {fetch"
    "('/api/status').then(r => r.json()).then(d => {const s = d.stats || {};const c = d.cartridges || {};"
    "curCard = d.active_cartridge || 'familiar';document.querySelectorAll('.pill-btn').forEach(b => b.cla"
    "ssList.remove('active'));const activeBtn = document.getElementById('tab-' + curCard);if (activeBtn) "
    "activeBtn.classList.add('active');document.querySelectorAll('.card').forEach(c => c.classList.remove"
    "('highlight'));const activeCard = document.getElementById('card-' + curCard);if (activeCard) activeC"
    "ard.classList.add('highlight');if (c.familiar) {document.getElementById('affinityVal').innerText = c"
    ".familiar.affinity || 88;}if (c.memo) {document.getElementById('memoCountTag').innerText = (c.memo.c"
    "ount || 0) + ' 条';}if (c.zen) {document.getElementById('meritVal').innerText = c.zen.total_merit || "
    "s.merit || 0;}if (c.clock) {const sec = c.clock.remain_s || 0;const m = String(Math.floor(sec / 60))"
    ".padStart(2, '0');const sc = String(sec % 60).padStart(2, '0');document.getElementById('pomoRemain')"
    ".innerText = c.clock.is_pomodoro ? (m + ':' + sc) : '25:00';document.getElementById('pomoStatusTag')"
    ".innerText = c.clock.is_pomodoro ? '🍅 专注中' : '待机';}document.getElementById('tokensVal').innerText = "
    "s.total_tokens || 0;document.getElementById('latencyVal').innerText = (s.last_latency_ms || 0) + ' m"
    "s';if (d.storage) updateStorageInfo(d.storage);}).catch(e => {});}setInterval(refresh, 1500);refresh"
    "();function switchCartridge(id) {fetch('/api/cartridge/switch', {method: 'POST',body: JSON.stringify"
    "({id: id})}).then(() => refresh());}function doAction(act) {fetch('/api/action', {method: 'POST',bod"
    "y: JSON.stringify({action: act})}).then(() => refresh());}function addMemo() {const t = document.get"
    "ElementById('memoInput').value.trim();if (!t) return;fetch('/api/memo/add', {method: 'POST',body: JS"
    "ON.stringify({content: t})}).then(() => {document.getElementById('lastMemo').innerText = t;document."
    "getElementById('memoInput').value = '';refresh();});}function loadConfig() {fetch('/api/config').the"
    "n(r => r.json()).then(d => {if (d.has_key && d.api_key_masked) {document.getElementById('apiKey').pl"
    "aceholder = '已配置 (' + d.api_key_masked + ')';}if (d.model) {document.getElementById('modelName').val"
    "ue = d.model;}if (d.prompt) {document.getElementById('agentPrompt').value = d.prompt;}}).catch(e => "
    "{});}function saveAgentConfig() {const k = document.getElementById('apiKey').value.trim();const m = "
    "document.getElementById('modelName').value.trim();const pr = document.getElementById('agentPrompt')."
    "value.trim();fetch('/api/config', {method: 'POST',headers: {'Content-Type': 'application/json'},body"
    ": JSON.stringify({api_key: k, model: m, prompt: pr})}).then(r => r.json()).then(d => {alert('✅ Agent"
    " 配置已保存并热加载至开发板！');loadConfig();}).catch(e => alert('保存失败'));}function resetWifi() {if (confirm('确认重置"
    " Wi-Fi 并返回 SoftAP 独立热点配网模式？')) {fetch('/api/wifi/reset', {method: 'POST'}).then(() => alert('设备正在重置网"
    "络并开启热点...'));}}loadConfig();/* ========================================================* 外置 TF 卡与存储管"
    "理器前端逻辑* ======================================================== */let curSdPath = '/';function upda"
    "teStorageInfo(st) {if (!st) return;if (st.data_dir) document.getElementById('dataBaseDir').innerText"
    " = st.data_dir;if (st.temp_dir) document.getElementById('tempBaseDir').innerText = st.temp_dir;const"
    " badge = document.getElementById('sdcardMountBadge');const pbar = document.getElementById('sdcardPro"
    "gressBar');if (st.sdcard_mounted) {badge.innerText = '● 已挂载就绪';badge.style.color = 'var(--accent-sub"
    ")';badge.style.borderColor = 'rgba(0, 255, 136, 0.4)';document.getElementById('sdcardMountPoint').in"
    "nerText = st.sdcard_mount_point || '/mnt/sdcard';document.getElementById('sdcardUsedPct').innerText "
    "= (st.sdcard_used_pct || 0) + '%';pbar.style.width = Math.min(100, Math.max(0, st.sdcard_used_pct ||"
    " 0)) + '%';const totalMb = st.sdcard_total_mb || 0;const freeMb = st.sdcard_free_mb || 0;const usedM"
    "b = totalMb >= freeMb ? (totalMb - freeMb) : 0;document.getElementById('sdcardTotalMb').innerText = "
    "totalMb;document.getElementById('sdcardUsedMb').innerText = usedMb;} else {badge.innerText = '○ 未检测到"
    " TF 卡';badge.style.color = 'var(--muted)';badge.style.borderColor = 'var(--border)';pbar.style.width"
    " = '0%';}}function formatBytes(bytes) {if (!bytes || bytes === 0) return '0 B';const k = 1024;const "
    "sizes = ['B', 'KB', 'MB', 'GB'];const i = Math.floor(Math.log(bytes) / Math.log(k));return (bytes / "
    "Math.pow(k, i)).toFixed(1) + ' ' + sizes[i];}function sdcardRefreshList() {fetch('/api/sdcard/list?p"
    "ath=' + encodeURIComponent(curSdPath)).then(r => r.json()).then(d => {document.getElementById('curre"
    "ntPathDisplay').innerText = curSdPath;const tbody = document.getElementById('sdcardFileList');if (!d"
    ".success || !d.items) {tbody.innerHTML = '<tr><td colspan=\"3\" style=\"padding:16px; text-align:cen"
    "ter; color:#ff5555\">读取失败: ' + (d.error || '未知错误') + '</td></tr>';return;}if (d.items.length === 0) "
    "{tbody.innerHTML = '<tr><td colspan=\"3\" style=\"padding:16px; text-align:center; color:var(--muted"
    ")\">当前目录为空</td></tr>';return;}// 文件夹排在前面，按名称字母升序d.items.sort((a, b) => (b.is_dir - a.is_dir) || a.na"
    "me.localeCompare(b.name));let html = '';d.items.forEach(it => {const fullItemPath = (curSdPath === '"
    "/' ? '' : curSdPath) + '/' + it.name;const icon = it.is_dir ? '📁' : '📄';const nameClick = it.is_dir?"
    " `onclick=\"sdcardGoPath('${fullItemPath}')\" style=\"cursor:pointer; color:var(--accent); font-weig"
    "ht:600;\"`: `style=\"color:#e6edf3;\"`;const sizeStr = it.is_dir ? '<span style=\"color:var(--muted)"
    "\">[目录]</span>' : formatBytes(it.size);let actions = '';if (!it.is_dir) {actions += `<a href=\"/api/"
    "sdcard/download?path=${encodeURIComponent(fullItemPath)}\" download=\"${it.name}\" style=\"color:var"
    "(--accent); text-decoration:none; margin-right:8px;\">⬇️下载</a>`;}actions += `<a href=\"javascript:vo"
    "id(0)\" onclick=\"sdcardDelete('${fullItemPath}', ${it.is_dir})\" style=\"color:#ff6b6b; text-decora"
    "tion:none;\">🗑️删除</a>`;html += `<tr style=\"border-bottom:1px solid rgba(255,255,255,0.04);\"><td st"
    "yle=\"padding:8px 12px;\"><span style=\"margin-right:6px;\">${icon}</span><span ${nameClick}>${it.na"
    "me}</span></td><td style=\"padding:8px 12px; color:var(--muted);\">${sizeStr}</td><td style=\"paddin"
    "g:8px 12px; text-align:right;\">${actions}</td></tr>`;});tbody.innerHTML = html;}).catch(e => {docum"
    "ent.getElementById('sdcardFileList').innerHTML = '<tr><td colspan=\"3\" style=\"padding:16px; text-a"
    "lign:center; color:#ff5555\">无法连接至开发板端侧服务</td></tr>';});}function sdcardGoPath(path) {curSdPath = pa"
    "th.startsWith('/') ? path : '/' + path;sdcardRefreshList();}function sdcardGoUp() {if (curSdPath ==="
    " '/' || !curSdPath) return;const parts = curSdPath.split('/').filter(Boolean);parts.pop();curSdPath "
    "= '/' + parts.join('/');sdcardRefreshList();}function sdcardMkdir() {const name = document.getElemen"
    "tById('newDirName').value.trim();if (!name) return;const targetPath = (curSdPath === '/' ? '' : curS"
    "dPath) + '/' + name;fetch('/api/sdcard/mkdir', {method: 'POST',headers: {'Content-Type': 'applicatio"
    "n/json'},body: JSON.stringify({path: targetPath})}).then(r => r.json()).then(d => {if (d.success) {d"
    "ocument.getElementById('newDirName').value = '';sdcardRefreshList();} else {alert('创建目录失败: ' + (d.er"
    "ror || '权限或路径非法'));}}).catch(e => alert('请求失败'));}function sdcardUploadText() {const fname = documen"
    "t.getElementById('uploadFileName').value.trim();const content = document.getElementById('uploadFileC"
    "ontent').value;if (!fname) {alert('请输入目标文件名');return;}const targetPath = (curSdPath === '/' ? '' : c"
    "urSdPath) + '/' + fname;fetch('/api/sdcard/upload', {method: 'POST',headers: {'Content-Type': 'appli"
    "cation/json'},body: JSON.stringify({path: targetPath, content: content})}).then(r => r.json()).then("
    "d => {if (d.success) {alert('✅ 文件已成功保存至 TF 卡: ' + targetPath);document.getElementById('uploadFileNam"
    "e').value = '';document.getElementById('uploadFileContent').value = '';sdcardRefreshList();} else {a"
    "lert('保存失败: ' + (d.error || '写入错误'));}}).catch(e => alert('上传异常'));}function handleLocalFileSelected"
    "(input) {if (input.files && input.files[0]) {const file = input.files[0];document.getElementById('up"
    "loadFileName').value = file.name;const reader = new FileReader();reader.onload = function(e) {docume"
    "nt.getElementById('uploadFileContent').value = e.target.result;};reader.readAsText(file);}}function "
    "sdcardDelete(path, isDir) {const typeStr = isDir ? '目录' : '文件';if (!confirm(`确认永久删除该${typeStr}：\\n${"
    "path} ？`)) return;fetch('/api/sdcard/delete', {method: 'POST',headers: {'Content-Type': 'application"
    "/json'},body: JSON.stringify({path: path})}).then(r => r.json()).then(d => {if (d.success) {sdcardRe"
    "freshList();} else {alert('删除失败: ' + (d.error || '请确认目录是否为空'));}}).catch(e => alert('删除请求异常'));}// 初"
    "始化加载 TF 卡文件列表sdcardRefreshList();/* ========================================================* 实时系统日志"
    "流 (增量游标消费 + 语法着色 + 过滤)* ======================================================== */let logCursor = 0"
    ";let logIsPaused = false;let logAutoScroll = true;let logLinesData = [];const MAX_LOG_LINES = 1500;f"
    "unction parseLogLine(raw) {if (!raw) return null;let level = 'I';if (raw.includes('[E]') || raw.incl"
    "udes('ERROR') || raw.includes('<3>')) level = 'E';else if (raw.includes('[W]') || raw.includes('WARN"
    "') || raw.includes('<4>')) level = 'W';else if (raw.includes('[D]') || raw.includes('DEBUG') || raw."
    "includes('<7>')) level = 'D';else if (raw.includes('[V]') || raw.includes('VERBOSE')) level = 'V';el"
    "se if (raw.includes('[I]') || raw.includes('INFO') || raw.includes('<6>')) level = 'I';return { raw:"
    " raw, level: level };}function renderLogEntry(entry) {const div = document.createElement('div');div."
    "className = 'log-line';let lvlClass = 'log-lvl-' + entry.level;div.innerHTML = `<span class=\"${lvlC"
    "lass}\">${escapeHtml(entry.raw)}</span>`;return div;}function escapeHtml(str) {return str.replace(/&"
    "/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');}function fetchLogs() {if (logIsPaused) ret"
    "urn;fetch('/api/logs?cursor=' + logCursor).then(r => r.json()).then(d => {if (d.cursor !== undefined"
    ") {logCursor = d.cursor;document.getElementById('logCursorTag').innerText = 'Cursor: ' + logCursor +"
    " ' B';}if (d.logs && d.logs.length > 0) {const lines = d.logs.split('\\n');const term = document.get"
    "ElementById('terminalWindow');const kw = document.getElementById('logFilterInput').value.trim().toLo"
    "werCase();const minLvl = document.getElementById('logLevelSelect').value;for (let line of lines) {if"
    " (!line.trim()) continue;const entry = parseLogLine(line);logLinesData.push(entry);if (logLinesData."
    "length > MAX_LOG_LINES) {logLinesData.shift();}if (matchesFilter(entry, kw, minLvl)) {term.appendChi"
    "ld(renderLogEntry(entry));}}while (term.children.length > MAX_LOG_LINES) {term.removeChild(term.firs"
    "tChild);}if (logAutoScroll) {term.scrollTop = term.scrollHeight;}}}).catch(e => {});}function matche"
    "sFilter(entry, kw, minLvl) {if (kw && !entry.raw.toLowerCase().includes(kw)) return false;if (minLvl"
    " === 'all') return true;const order = { 'DEBUG': 1, 'INFO': 2, 'WARN': 3, 'ERROR': 4 };const entryVa"
    "l = { 'D': 1, 'V': 1, 'I': 2, 'W': 3, 'E': 4 }[entry.level] || 2;const targetVal = order[minLvl] || "
    "0;return entryVal >= targetVal;}function applyLogFilter() {const term = document.getElementById('ter"
    "minalWindow');term.innerHTML = '';const kw = document.getElementById('logFilterInput').value.trim()."
    "toLowerCase();const minLvl = document.getElementById('logLevelSelect').value;const frag = document.c"
    "reateDocumentFragment();for (let entry of logLinesData) {if (matchesFilter(entry, kw, minLvl)) {frag"
    ".appendChild(renderLogEntry(entry));}}term.appendChild(frag);if (logAutoScroll) term.scrollTop = ter"
    "m.scrollHeight;}function changeLogLevel(val) {applyLogFilter();if (val !== 'all') {fetch('/api/logs/"
    "level', {method: 'POST',headers: {'Content-Type': 'application/json'},body: JSON.stringify({level: v"
    "al})}).catch(e => {});}}function toggleAutoScroll() {logAutoScroll = !logAutoScroll;const btn = docu"
    "ment.getElementById('autoScrollBtn');btn.innerText = logAutoScroll ? '⏬ 滚屏: 开' : '⏸️ 滚屏: 关';btn.styl"
    "e.borderColor = logAutoScroll ? 'var(--accent)' : 'var(--border)';}function toggleLogPause() {logIsP"
    "aused = !logIsPaused;const btn = document.getElementById('pauseLogBtn');const badge = document.getEl"
    "ementById('logStreamBadge');if (logIsPaused) {btn.innerText = '▶️ 继续';badge.innerText = '⏸️ 已暂停';bad"
    "ge.style.color = 'var(--muted)';} else {btn.innerText = '⏸️ 暂停';badge.innerText = '● 实时监听中';badge.st"
    "yle.color = 'var(--accent-sub)';}}function clearLocalLogs() {logLinesData = [];document.getElementBy"
    "Id('terminalWindow').innerHTML = '<div class=\"log-line\" style=\"color:var(--muted)\">[UI] 视图已清空</d"
    "iv>';}function clearDeviceLogs() {if (!confirm('确认清空端侧循环日志缓冲区？')) return;fetch('/api/logs/clear', { "
    "method: 'POST' }).then(r => r.json()).then(d => {clearLocalLogs();logCursor = 0;document.getElementB"
    "yId('logCursorTag').innerText = 'Cursor: 0 B';}).catch(e => alert('清空失败'));}function exportLogs() {c"
    "onst text = logLinesData.map(e => e.raw).join('\\n');const blob = new Blob([text], {type: 'text/plai"
    "n;charset=utf-8'});const url = URL.createObjectURL(blob);const a = document.createElement('a');a.hre"
    "f = url;a.download = 'phoenix_logs_' + new Date().toISOString().replace(/[:.]/g, '-') + '.log';a.cli"
    "ck();URL.revokeObjectURL(url);}const termEl = document.getElementById('terminalWindow');termEl.addEv"
    "entListener('scroll', () => {const isAtBottom = termEl.scrollHeight - termEl.scrollTop - termEl.clie"
    "ntHeight < 30;if (!isAtBottom && logAutoScroll) {toggleAutoScroll();}});setInterval(fetchLogs, 900);"
    "fetchLogs();</script></body></html>";

const char *phoenix_web_asset_get_setup_html(void)
{
    return s_setup_html;
}

size_t phoenix_web_asset_get_setup_html_len(void)
{
    return sizeof(s_setup_html) - 1;
}

const char *phoenix_web_asset_get_ble_setup_html(void)
{
    return s_ble_setup_html;
}

size_t phoenix_web_asset_get_ble_setup_html_len(void)
{
    return sizeof(s_ble_setup_html) - 1;
}

const char *phoenix_web_asset_get_dashboard_html(void)
{
    return s_dashboard_html;
}

size_t phoenix_web_asset_get_dashboard_html_len(void)
{
    return sizeof(s_dashboard_html) - 1;
}
