/**
 * @file web_assets.c
 * @brief Embedded Web Page Assets Implementation (Auto-generated)
 * @author OpenVela Contest 2026 Team 145
 */

#include "web_assets.h"
#include <string.h>

static const char s_setup_html[] =
    "<!DOCTYPE html><html lang=\"zh-CN\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\""
    "width=device-width, initial-scale=1.0\"><title>Gemini-S1 智能硬件热点配网</title><style>:root {--bg: #080c14"
    ";--card: #101726;--border: #1c2a44;--accent: #00e5ff;--accent-sub: #00ff88;--text: #e6edf3;--muted: "
    "#8b9eb5;}body {margin: 0;padding: 24px 16px;background: var(--bg);color: var(--text);font-family: -a"
    "pple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, sans-serif;}.box {max-width: 440px;margin: 0 "
    "auto;background: var(--card);border: 1px solid var(--border);border-radius: 16px;padding: 24px;box-s"
    "hadow: 0 12px 32px rgba(0, 0, 0, 0.5);position: relative;}.box::before {content: '';position: absolu"
    "te;top: 0;left: 0;right: 0;height: 3px;background: linear-gradient(90deg, var(--accent), var(--accen"
    "t-sub));border-radius: 16px 16px 0 0;}h1 {color: var(--accent);font-size: 20px;margin: 0 0 6px;text-"
    "align: center;display: flex;align-items: center;justify-content: center;gap: 8px;}p {font-size: 13px"
    ";color: var(--muted);line-height: 1.5;margin: 0 0 16px;text-align: center;}.scan-bar {display: flex;"
    "justify-content: space-between;align-items: center;margin-top: 14px;margin-bottom: 6px;}.scan-title "
    "{font-size: 13px;font-weight: 700;color: var(--accent);display: flex;align-items: center;gap: 6px;}."
    "scan-btn {background: #182842;border: 1px solid #233b63;color: var(--accent);padding: 4px 12px;borde"
    "r-radius: 14px;font-size: 12px;font-weight: 600;cursor: pointer;transition: 0.2s;}.scan-btn:hover {b"
    "ackground: #22375a;}label {font-size: 12px;color: var(--muted);font-weight: 600;margin-top: 12px;dis"
    "play: block;}input, select {width: 100%;box-sizing: border-box;padding: 11px;margin-top: 6px;border-"
    "radius: 8px;border: 1px solid var(--border);background: #090d16;color: #fff;font-size: 13px;font-fam"
    "ily: inherit;}input:focus, select:focus {border-color: var(--accent);outline: none;}.wifi-badges {di"
    "splay: flex;flex-wrap: wrap;gap: 6px;margin-top: 8px;}.wifi-badge {background: #0a0f1c;border: 1px s"
    "olid rgba(255, 255, 255, 0.06);padding: 6px 10px;border-radius: 6px;font-size: 12px;cursor: pointer;"
    "display: flex;align-items: center;gap: 4px;color: #c0d2e8;transition: 0.2s;}.wifi-badge:hover {borde"
    "r-color: var(--accent);color: var(--accent);background: #131d30;}button.submit-btn {width: 100%;back"
    "ground: var(--accent);color: #04060a;border: none;border-radius: 8px;padding: 12px;font-size: 15px;f"
    "ont-weight: bold;cursor: pointer;margin-top: 20px;transition: 0.2s;}button.submit-btn:hover {backgro"
    "und: #33ebff;transform: translateY(-1px);}.tip {background: #0c1422;border-left: 3px solid var(--acc"
    "ent);padding: 10px 12px;margin-top: 16px;border-radius: 6px;font-size: 12px;color: #a0b4cc;line-heig"
    "ht: 1.5;}.status-pill {font-size: 11px;padding: 2px 6px;border-radius: 10px;background: #182842;colo"
    "r: var(--accent-sub);}</style></head><body><div class=\"box\"><h1>📡 Gemini-S1 硬件热点配网</h1><p>设备处于 Sof"
    "tAP 独立热点模式。请搜索并选择周边 Wi-Fi 连入网络；联网后可在控制中心或伴侣看板中自由配置 Agent 模型与桌面玩法。</p><div class=\"scan-bar\"><span c"
    "lass=\"scan-title\">📶 周边 Wi-Fi 热点</span><button class=\"scan-btn\" onclick=\"scanWifi()\">🔄 刷新扫描</bu"
    "tton></div><select id=\"wifiSelect\" onchange=\"onSelectChange()\"><option value=\"\">⏳ 正在搜索周边 Wi-Fi"
    "...</option></select><div class=\"wifi-badges\" id=\"quickList\"></div><div id=\"manualBox\" style=\""
    "display:none;\"><label>手动输入 SSID:</label><input id=\"ssid\" type=\"text\" placeholder=\"输入无线网络名称 (SS"
    "ID)\"></div><label>Wi-Fi 密码 (PSK):</label><input id=\"psk\" type=\"password\" placeholder=\"请输入密码 (开"
    "放网络留空)\"><div id=\"authTip\" style=\"font-size:11px; color:#00ff88; margin-top:4px; display:none;\">"
    "</div><button class=\"submit-btn\" onclick=\"connectWifi()\">🚀 保存凭证并连接 Wi-Fi</button><div class=\"ti"
    "p\" id=\"msg\">💡 连接后设备将切换并获取局域网 IP。请将手机/电脑连入同一 Wi-Fi，访问小屏顶部显示的 IP 即可打开极客伴侣看板配置 Agent。</div></div><sc"
    "ript>let scanData = [];function scanWifi() {const sel = document.getElementById('wifiSelect');sel.in"
    "nerHTML = '<option value=\"\">⏳ 正在搜索周边 Wi-Fi...</option>';document.getElementById('quickList').inner"
    "HTML = '';fetch('/api/wifi/scan').then(r => r.json()).then(d => {scanData = d.aps || [];sel.innerHTM"
    "L = '';const qk = document.getElementById('quickList');if (scanData.length === 0) {sel.innerHTML = '"
    "<option value=\"__manual__\">未搜到热点 - 手动输入 SSID</option>';return;}sel.innerHTML = '<option value=\"\""
    ">-- 请选择 Wi-Fi 热点 (' + scanData.length + '个可用) --</option>';scanData.forEach(ap => {const opt = docum"
    "ent.createElement('option');opt.value = ap.ssid;opt.text = '📶 ' + ap.ssid + ' (' + ap.rssi + 'dBm · "
    "' + ap.auth + ')';sel.appendChild(opt);const bd = document.createElement('div');bd.className = 'wifi"
    "-badge';bd.innerHTML = '📶 ' + ap.ssid + ' <span class=\"status-pill\">' + ap.auth + '</span>';bd.onc"
    "lick = () => {sel.value = ap.ssid;onSelectChange();};qk.appendChild(bd);});const mOpt = document.cre"
    "ateElement('option');mOpt.value = '__manual__';mOpt.text = '➕ 手动输入隐藏 Wi-Fi...';sel.appendChild(mOpt)"
    ";}).catch(e => {sel.innerHTML = '<option value=\"__manual__\">扫描失败 - 手动输入 SSID</option>';});}functio"
    "n onSelectChange() {const val = document.getElementById('wifiSelect').value;const mb = document.getE"
    "lementById('manualBox');const tip = document.getElementById('authTip');if (val === '__manual__') {mb"
    ".style.display = 'block';tip.style.display = 'none';} else {mb.style.display = 'none';document.getEl"
    "ementById('ssid').value = val;const ap = scanData.find(x => x.ssid === val);if (ap && ap.auth === 'O"
    "PEN') {tip.innerText = '● 该网络为开放免密网络，密码可留空直接连接';tip.style.display = 'block';document.getElementById("
    "'psk').value = '';} else {tip.style.display = 'none';}}}function connectWifi() {let s = document.get"
    "ElementById('wifiSelect').value;if (s === '__manual__' || !s) {s = document.getElementById('ssid').v"
    "alue.trim();}if (!s) {alert('请先选择或输入 Wi-Fi 名称！');return;}const p = document.getElementById('psk').va"
    "lue;document.getElementById('msg').innerHTML = '⏳ 正在连接 Wi-Fi [' + s + ']，请稍候...';fetch('/api/wifi/co"
    "nnect', {method: 'POST',headers: {'Content-Type': 'application/json'},body: JSON.stringify({ssid: s,"
    " psk: p})}).then(r => r.json()).then(d => {document.getElementById('msg').innerHTML = '✅ 联网指令已下发！设备正"
    "在获取局域网 IP。<br>请将电脑/手机连入同一 Wi-Fi，访问小屏显示的 IP 进入伴侣看板配置 Agent！';}).catch(e => {document.getElementById('"
    "msg').innerHTML = '⚠️ 网络请求已提交，设备正在切换并连入局域网。';});}scanWifi();</script></body></html>";

static const char s_dashboard_html[] =
    "<!DOCTYPE html><html lang=\"zh-CN\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\""
    "width=device-width, initial-scale=1.0\"><title>Phoenix HoloDesk-S1 Geek Dashboard</title><style>:roo"
    "t {--bg: #080c14;--card: #101726;--border: #1c2a44;--accent: #00e5ff;--accent-sub: #00ff88;--text: #"
    "e6edf3;--muted: #8b9eb5;}body {margin: 0;padding: 24px;background: var(--bg);color: var(--text);font"
    "-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, sans-serif;}.wrap {max-width: 960p"
    "x;margin: 0 auto;}header {display: flex;justify-content: space-between;align-items: center;margin-bo"
    "ttom: 20px;border-bottom: 1px solid var(--border);padding-bottom: 14px;}h1 {color: var(--accent);fon"
    "t-size: 20px;margin: 0;display: flex;align-items: center;gap: 8px;font-weight: 700;}.badge {backgrou"
    "nd: #182842;border: 1px solid #233b63;color: var(--accent);padding: 4px 12px;border-radius: 20px;fon"
    "t-size: 12px;font-weight: 600;}.selector {display: flex;gap: 10px;margin-bottom: 20px;overflow-x: au"
    "to;padding-bottom: 4px;}.pill-btn {background: var(--card);border: 1px solid var(--border);color: va"
    "r(--text);padding: 10px 16px;border-radius: 24px;cursor: pointer;font-size: 13px;font-weight: 600;di"
    "splay: flex;align-items: center;gap: 6px;transition: 0.2s;white-space: nowrap;}.pill-btn:hover {bord"
    "er-color: var(--accent);color: var(--accent);}.pill-btn.active {background: linear-gradient(135deg, "
    "rgba(0, 229, 255, 0.15), rgba(0, 255, 136, 0.15));border-color: var(--accent);color: #fff;box-shadow"
    ": 0 0 16px rgba(0, 229, 255, 0.25);}.grid {display: grid;grid-template-columns: repeat(auto-fit, min"
    "max(280px, 1fr));gap: 16px;margin-bottom: 20px;}.card {background: var(--card);border: 1px solid var"
    "(--border);border-radius: 14px;padding: 18px;box-shadow: 0 8px 24px rgba(0, 0, 0, 0.4);position: rel"
    "ative;overflow: hidden;}.card::before {content: '';position: absolute;top: 0;left: 0;right: 0;height"
    ": 2px;background: linear-gradient(90deg, transparent, var(--border), transparent);}.card.highlight::"
    "before {background: linear-gradient(90deg, var(--accent), var(--accent-sub));}.card-head {display: f"
    "lex;justify-content: space-between;align-items: center;margin-bottom: 12px;}.card-title {font-size: "
    "15px;font-weight: bold;color: var(--accent);display: flex;align-items: center;gap: 6px;}.metric-row "
    "{display: flex;gap: 12px;margin-bottom: 14px;}.m-block {background: #0a0f1c;padding: 10px;border-rad"
    "ius: 8px;flex: 1;text-align: center;border: 1px solid rgba(255, 255, 255, 0.04);}.m-lbl {font-size: "
    "11px;color: var(--muted);}.m-val {font-size: 20px;font-weight: bold;color: var(--accent-sub);margin-"
    "top: 4px;}input, button {width: 100%;box-sizing: border-box;padding: 10px;border-radius: 8px;border:"
    " 1px solid var(--border);background: #090d16;color: #fff;font-size: 13px;}button {background: var(--"
    "accent);color: #04060a;border: none;font-weight: bold;cursor: pointer;margin-top: 10px;transition: 0"
    ".2s;}button:hover {background: #33ebff;transform: translateY(-1px);}.btn-secondary {background: #182"
    "842;color: #9bc0e7;border: 1px solid #233b63;}.btn-secondary:hover {background: #22375a;color: #fff;"
    "}.btn-warn {background: #d29922;color: #000;}.btn-warn:hover {background: #ebb034;}.memo-item {backg"
    "round: #0a0f1c;padding: 8px 12px;border-radius: 6px;font-size: 12px;margin-bottom: 6px;color: #c0d2e"
    "8;border-left: 2px solid var(--accent);}</style></head><body><div class=\"wrap\"><header><h1>💎 Phoen"
    "ix HoloDesk-S1 极客伴侣看板</h1><div class=\"badge\" id=\"connStatus\">● 局域网已连接</div></header><div class=\""
    "selector\"><div class=\"pill-btn\" id=\"tab-familiar\" onclick=\"switchCartridge('familiar')\">🐱 桌面使"
    "魔</div><div class=\"pill-btn\" id=\"tab-memo\" onclick=\"switchCartridge('memo')\">💡 灵感外脑</div><div "
    "class=\"pill-btn\" id=\"tab-clock\" onclick=\"switchCartridge('clock')\">⏰ 翻页时钟</div><div class=\"pi"
    "ll-btn\" id=\"tab-zen\" onclick=\"switchCartridge('zen')\">🪷 赛博木鱼</div></div><div class=\"grid\"><di"
    "v class=\"card\" id=\"card-familiar\"><div class=\"card-head\"><div class=\"card-title\">🐱 桌面使魔萌宠</d"
    "iv><span class=\"badge\" id=\"moodTag\">陪伴中</span></div><div class=\"metric-row\"><div class=\"m-blo"
    "ck\"><div class=\"m-lbl\">使魔亲密度</div><div class=\"m-val\" id=\"affinityVal\">--</div></div><div clas"
    "s=\"m-block\"><div class=\"m-lbl\">元气饱腹度</div><div class=\"m-val\">95%</div></div></div><button clas"
    "s=\"btn-secondary\" onclick=\"doAction('pet')\">🐾 远程轻抚使魔撒娇</button></div><div class=\"card\" id=\"ca"
    "rd-memo\"><div class=\"card-head\"><div class=\"card-title\">💡 灵感外脑速记</div><span class=\"badge\" id="
    "\"memoCountTag\">3 条</span></div><div class=\"memo-item\" id=\"lastMemo\">正在同步端侧备忘...</div><input id"
    "=\"memoInput\" type=\"text\" placeholder=\"在此输入闪念，即刻存入端侧外脑\"><button onclick=\"addMemo()\">💡 推入灵感外脑<"
    "/button></div><div class=\"card\" id=\"card-clock\"><div class=\"card-head\"><div class=\"card-title"
    "\">⏰ 翻页时钟 & 专注流</div><span class=\"badge\" id=\"pomoStatusTag\">待命</span></div><div class=\"metric-r"
    "ow\"><div class=\"m-block\"><div class=\"m-lbl\">专注倒计时</div><div class=\"m-val\" id=\"pomoRemain\">-"
    "-:--</div></div><div class=\"m-block\"><div class=\"m-lbl\">推理延迟</div><div class=\"m-val\" id=\"late"
    "ncyVal\">-- ms</div></div></div><button class=\"btn-secondary\" onclick=\"doAction('pomo_toggle')\">"
    "🍅 开启 / 暂停番茄专注</button></div><div class=\"card\" id=\"card-zen\"><div class=\"card-head\"><div class="
    "\"card-title\">🪷 极客禅意木鱼</div><span class=\"badge\">消除焦虑</span></div><div class=\"metric-row\"><div c"
    "lass=\"m-block\"><div class=\"m-lbl\">累计功德数</div><div class=\"m-val\" id=\"meritVal\">--</div></div>"
    "<div class=\"m-block\"><div class=\"m-lbl\">消耗 Tokens</div><div class=\"m-val\" id=\"tokensVal\">--<"
    "/div></div></div><button onclick=\"doAction('knock_fish')\">🪷 敲击木鱼 (功德+1)</button></div></div><div c"
    "lass=\"card\" style=\"margin-bottom:20px;\"><div class=\"card-head\"><div class=\"card-title\">⚙️ 云端"
    "大模型与 Agent 配置中心</div><span class=\"badge\" id=\"cfgStatusBadge\">端侧热加载</span></div><div style=\"disp"
    "lay:grid; grid-template-columns:repeat(auto-fit,minmax(260px,1fr)); gap:12px; margin-bottom:10px;\">"
    "<div><div style=\"font-size:12px; color:var(--muted); margin-bottom:4px; font-weight:600;\">大模型 API "
    "Key:</div><input id=\"apiKey\" type=\"password\" placeholder=\"输入云端 API Key (如 sk-xxxx)\"></div><div"
    "><div style=\"font-size:12px; color:var(--muted); margin-bottom:4px; font-weight:600;\">大模型名称 (Model"
    "):</div><input id=\"modelName\" type=\"text\" placeholder=\"如 deepseek-chat 或 gpt-4o-mini\"></div></"
    "div><div style=\"font-size:12px; color:var(--muted); margin-bottom:4px; font-weight:600;\">Agent 系统人"
    "设提示词 (Prompt):</div><textarea id=\"agentPrompt\" rows=\"2\" style=\"width:100%; box-sizing:border-bo"
    "x; padding:10px; border-radius:8px; border:1px solid var(--border); background:#090d16; color:#fff; "
    "font-size:13px; resize:none;\" placeholder=\"如：你是一个贴心的赛博桌面极客助手，语气温和简短\"></textarea><div style=\"disp"
    "lay:flex; gap:10px; margin-top:12px;\"><button onclick=\"saveAgentConfig()\">💾 保存并热加载至开发板</button><b"
    "utton class=\"btn-warn\" onclick=\"resetWifi()\">📡 重置 Wi-Fi 并返回热点</button></div></div><div class=\"c"
    "ard\" id=\"card-storage\"><div class=\"card-head\"><div class=\"card-title\">📁 外置 MicroSD / TF 卡存储管理"
    "</div><span class=\"badge\" id=\"sdcardMountBadge\">探测中...</span></div><div style=\"background:#090d"
    "16; border:1px solid var(--border); border-radius:10px; padding:12px; margin-bottom:16px;\"><div sty"
    "le=\"display:flex; justify-content:space-between; font-size:12px; margin-bottom:8px;\"><span style=\""
    "color:var(--muted)\">挂载目录: <b id=\"sdcardMountPoint\" style=\"color:var(--accent)\">/mnt/sdcard</b><"
    "/span><span style=\"color:var(--muted)\">已用: <b id=\"sdcardUsedPct\" style=\"color:var(--accent-sub)"
    "\">--%</b> (<span id=\"sdcardUsedMb\">0</span> MB / <span id=\"sdcardTotalMb\">0</span> MB)</span></"
    "div><div style=\"height:8px; background:#141c2c; border-radius:4px; overflow:hidden;\"><div id=\"sdc"
    "ardProgressBar\" style=\"width:0%; height:100%; background:linear-gradient(90deg, var(--accent), var"
    "(--accent-sub)); transition:width 0.4s ease;\"></div></div><div style=\"display:flex; gap:12px; marg"
    "in-top:10px; font-size:11px; color:var(--muted);\"><span>📌 持久配置: <code id=\"dataBaseDir\" style=\"co"
    "lor:#9bc0e7\">/data/phoenix</code></span><span>⚡ 中间分片: <code id=\"tempBaseDir\" style=\"color:#9bc0e"
    "7\">/tmp/phoenix</code></span></div></div><div style=\"display:flex; justify-content:space-between; "
    "align-items:center; flex-wrap:wrap; gap:8px; margin-bottom:12px;\"><div style=\"display:flex; align-"
    "items:center; gap:6px;\"><span style=\"font-size:12px; color:var(--muted)\">路径:</span><code id=\"cur"
    "rentPathDisplay\" style=\"background:#182842; color:var(--accent); padding:4px 8px; border-radius:6p"
    "x; font-size:12px; font-weight:bold;\">/</code><button class=\"btn-secondary\" style=\"margin:0; pad"
    "ding:4px 10px; font-size:11px; width:auto;\" onclick=\"sdcardGoUp()\">⬆️ 上一级</button><button class=\""
    "btn-secondary\" style=\"margin:0; padding:4px 10px; font-size:11px; width:auto;\" onclick=\"sdcardRe"
    "freshList()\">🔄 刷新</button></div><div style=\"display:flex; gap:6px;\"><button class=\"btn-secondary"
    "\" style=\"margin:0; padding:4px 10px; font-size:11px; width:auto;\" onclick=\"sdcardGoPath('/sounds"
    "')\">🎵 sounds</button><button class=\"btn-secondary\" style=\"margin:0; padding:4px 10px; font-size:"
    "11px; width:auto;\" onclick=\"sdcardGoPath('/logs')\">📜 logs</button><button class=\"btn-secondary\""
    " style=\"margin:0; padding:4px 10px; font-size:11px; width:auto;\" onclick=\"sdcardGoPath('/docs')\""
    ">📑 docs</button></div></div><div style=\"background:#090d16; border:1px solid var(--border); border-"
    "radius:8px; max-height:260px; overflow-y:auto; margin-bottom:16px;\"><table style=\"width:100%; bord"
    "er-collapse:collapse; font-size:12px; text-align:left;\"><thead><tr style=\"border-bottom:1px solid "
    "var(--border); color:var(--muted);\"><th style=\"padding:8px 12px;\">名称</th><th style=\"padding:8px "
    "12px; width:80px;\">大小</th><th style=\"padding:8px 12px; width:120px; text-align:right;\">操作</th></t"
    "r></thead><tbody id=\"sdcardFileList\"><tr><td colspan=\"3\" style=\"padding:16px; text-align:center"
    "; color:var(--muted)\">正在读取 TF 卡文件系统...</td></tr></tbody></table></div><div style=\"display:grid; gr"
    "id-template-columns:repeat(auto-fit,minmax(280px,1fr)); gap:12px;\"><div style=\"background:#0a0f1c;"
    " padding:12px; border-radius:8px; border:1px solid rgba(255,255,255,0.04);\"><div style=\"font-size:"
    "12px; color:var(--accent); font-weight:600; margin-bottom:6px;\">📁 新建子目录</div><div style=\"display:f"
    "lex; gap:8px;\"><input id=\"newDirName\" type=\"text\" placeholder=\"目录名称 (如 music)\" style=\"paddin"
    "g:8px; font-size:12px;\"><button style=\"margin:0; width:auto; padding:8px 14px; font-size:12px; whi"
    "te-space:nowrap;\" onclick=\"sdcardMkdir()\">新建</button></div></div><div style=\"background:#0a0f1c;"
    " padding:12px; border-radius:8px; border:1px solid rgba(255,255,255,0.04);\"><div style=\"font-size:"
    "12px; color:var(--accent-sub); font-weight:600; margin-bottom:6px;\">✍️ 写入文件 / 上传文本</div><input id=\""
    "uploadFileName\" type=\"text\" placeholder=\"文件名 (如 memo.txt)\" style=\"padding:8px; font-size:12px;"
    " margin-bottom:6px;\"><textarea id=\"uploadFileContent\" rows=\"2\" placeholder=\"文件内容 (纯文本、脚本或配置)\""
    " style=\"width:100%; box-sizing:border-box; padding:8px; border-radius:8px; border:1px solid var(--b"
    "order); background:#090d16; color:#fff; font-size:12px; resize:none;\"></textarea><div style=\"displ"
    "ay:flex; gap:8px; margin-top:6px;\"><input type=\"file\" id=\"localFileInput\" style=\"display:none;"
    "\" onchange=\"handleLocalFileSelected(this)\"><button class=\"btn-secondary\" style=\"margin:0; padd"
    "ing:6px 12px; font-size:11px; width:auto;\" onclick=\"document.getElementById('localFileInput').clic"
    "k()\">📂 选择本地文件</button><button style=\"margin:0; padding:6px 12px; font-size:11px; flex:1;\" onclick"
    "=\"sdcardUploadText()\">🚀 保存并写入 TF 卡</button></div></div></div></div></div><script>let curCard = 'fa"
    "miliar';function refresh() {fetch('/api/status').then(r => r.json()).then(d => {const s = d.stats ||"
    " {};const c = d.cartridges || {};curCard = d.active_cartridge || 'familiar';document.querySelectorAl"
    "l('.pill-btn').forEach(b => b.classList.remove('active'));const activeBtn = document.getElementById("
    "'tab-' + curCard);if (activeBtn) activeBtn.classList.add('active');document.querySelectorAll('.card'"
    ").forEach(c => c.classList.remove('highlight'));const activeCard = document.getElementById('card-' +"
    " curCard);if (activeCard) activeCard.classList.add('highlight');if (c.familiar) {document.getElement"
    "ById('affinityVal').innerText = c.familiar.affinity || 88;}if (c.memo) {document.getElementById('mem"
    "oCountTag').innerText = (c.memo.count || 0) + ' 条';}if (c.zen) {document.getElementById('meritVal')."
    "innerText = c.zen.total_merit || s.merit || 0;}if (c.clock) {const sec = c.clock.remain_s || 0;const"
    " m = String(Math.floor(sec / 60)).padStart(2, '0');const sc = String(sec % 60).padStart(2, '0');docu"
    "ment.getElementById('pomoRemain').innerText = c.clock.is_pomodoro ? (m + ':' + sc) : '25:00';documen"
    "t.getElementById('pomoStatusTag').innerText = c.clock.is_pomodoro ? '🍅 专注中' : '待机';}document.getElem"
    "entById('tokensVal').innerText = s.total_tokens || 0;document.getElementById('latencyVal').innerText"
    " = (s.last_latency_ms || 0) + ' ms';if (d.storage) updateStorageInfo(d.storage);}).catch(e => {});}s"
    "etInterval(refresh, 1500);refresh();function switchCartridge(id) {fetch('/api/cartridge/switch', {me"
    "thod: 'POST',body: JSON.stringify({id: id})}).then(() => refresh());}function doAction(act) {fetch('"
    "/api/action', {method: 'POST',body: JSON.stringify({action: act})}).then(() => refresh());}function "
    "addMemo() {const t = document.getElementById('memoInput').value.trim();if (!t) return;fetch('/api/me"
    "mo/add', {method: 'POST',body: JSON.stringify({content: t})}).then(() => {document.getElementById('l"
    "astMemo').innerText = t;document.getElementById('memoInput').value = '';refresh();});}function loadC"
    "onfig() {fetch('/api/config').then(r => r.json()).then(d => {if (d.has_key && d.api_key_masked) {doc"
    "ument.getElementById('apiKey').placeholder = '已配置 (' + d.api_key_masked + ')';}if (d.model) {documen"
    "t.getElementById('modelName').value = d.model;}if (d.prompt) {document.getElementById('agentPrompt')"
    ".value = d.prompt;}}).catch(e => {});}function saveAgentConfig() {const k = document.getElementById("
    "'apiKey').value.trim();const m = document.getElementById('modelName').value.trim();const pr = docume"
    "nt.getElementById('agentPrompt').value.trim();fetch('/api/config', {method: 'POST',headers: {'Conten"
    "t-Type': 'application/json'},body: JSON.stringify({api_key: k, model: m, prompt: pr})}).then(r => r."
    "json()).then(d => {alert('✅ Agent 配置已保存并热加载至开发板！');loadConfig();}).catch(e => alert('保存失败'));}functi"
    "on resetWifi() {if (confirm('确认重置 Wi-Fi 并返回 SoftAP 独立热点配网模式？')) {fetch('/api/wifi/reset', {method: '"
    "POST'}).then(() => alert('设备正在重置网络并开启热点...'));}}loadConfig();/* ===================================="
    "====================* 外置 TF 卡与存储管理器前端逻辑* ======================================================== */"
    "let curSdPath = '/';function updateStorageInfo(st) {if (!st) return;if (st.data_dir) document.getEle"
    "mentById('dataBaseDir').innerText = st.data_dir;if (st.temp_dir) document.getElementById('tempBaseDi"
    "r').innerText = st.temp_dir;const badge = document.getElementById('sdcardMountBadge');const pbar = d"
    "ocument.getElementById('sdcardProgressBar');if (st.sdcard_mounted) {badge.innerText = '● 已挂载就绪';badg"
    "e.style.color = 'var(--accent-sub)';badge.style.borderColor = 'rgba(0, 255, 136, 0.4)';document.getE"
    "lementById('sdcardMountPoint').innerText = st.sdcard_mount_point || '/mnt/sdcard';document.getElemen"
    "tById('sdcardUsedPct').innerText = (st.sdcard_used_pct || 0) + '%';pbar.style.width = Math.min(100, "
    "Math.max(0, st.sdcard_used_pct || 0)) + '%';const totalMb = st.sdcard_total_mb || 0;const freeMb = s"
    "t.sdcard_free_mb || 0;const usedMb = totalMb >= freeMb ? (totalMb - freeMb) : 0;document.getElementB"
    "yId('sdcardTotalMb').innerText = totalMb;document.getElementById('sdcardUsedMb').innerText = usedMb;"
    "} else {badge.innerText = '○ 未检测到 TF 卡';badge.style.color = 'var(--muted)';badge.style.borderColor ="
    " 'var(--border)';pbar.style.width = '0%';}}function formatBytes(bytes) {if (!bytes || bytes === 0) r"
    "eturn '0 B';const k = 1024;const sizes = ['B', 'KB', 'MB', 'GB'];const i = Math.floor(Math.log(bytes"
    ") / Math.log(k));return (bytes / Math.pow(k, i)).toFixed(1) + ' ' + sizes[i];}function sdcardRefresh"
    "List() {fetch('/api/sdcard/list?path=' + encodeURIComponent(curSdPath)).then(r => r.json()).then(d ="
    "> {document.getElementById('currentPathDisplay').innerText = curSdPath;const tbody = document.getEle"
    "mentById('sdcardFileList');if (!d.success || !d.items) {tbody.innerHTML = '<tr><td colspan=\"3\" sty"
    "le=\"padding:16px; text-align:center; color:#ff5555\">读取失败: ' + (d.error || '未知错误') + '</td></tr>';r"
    "eturn;}if (d.items.length === 0) {tbody.innerHTML = '<tr><td colspan=\"3\" style=\"padding:16px; tex"
    "t-align:center; color:var(--muted)\">当前目录为空</td></tr>';return;}// 文件夹排在前面，按名称字母升序d.items.sort((a, b)"
    " => (b.is_dir - a.is_dir) || a.name.localeCompare(b.name));let html = '';d.items.forEach(it => {cons"
    "t fullItemPath = (curSdPath === '/' ? '' : curSdPath) + '/' + it.name;const icon = it.is_dir ? '📁' :"
    " '📄';const nameClick = it.is_dir? `onclick=\"sdcardGoPath('${fullItemPath}')\" style=\"cursor:pointe"
    "r; color:var(--accent); font-weight:600;\"`: `style=\"color:#e6edf3;\"`;const sizeStr = it.is_dir ? "
    "'<span style=\"color:var(--muted)\">[目录]</span>' : formatBytes(it.size);let actions = '';if (!it.is_"
    "dir) {actions += `<a href=\"/api/sdcard/download?path=${encodeURIComponent(fullItemPath)}\" download"
    "=\"${it.name}\" style=\"color:var(--accent); text-decoration:none; margin-right:8px;\">⬇️下载</a>`;}ac"
    "tions += `<a href=\"javascript:void(0)\" onclick=\"sdcardDelete('${fullItemPath}', ${it.is_dir})\" s"
    "tyle=\"color:#ff6b6b; text-decoration:none;\">🗑️删除</a>`;html += `<tr style=\"border-bottom:1px solid"
    " rgba(255,255,255,0.04);\"><td style=\"padding:8px 12px;\"><span style=\"margin-right:6px;\">${icon}"
    "</span><span ${nameClick}>${it.name}</span></td><td style=\"padding:8px 12px; color:var(--muted);\">"
    "${sizeStr}</td><td style=\"padding:8px 12px; text-align:right;\">${actions}</td></tr>`;});tbody.inne"
    "rHTML = html;}).catch(e => {document.getElementById('sdcardFileList').innerHTML = '<tr><td colspan=\""
    "3\" style=\"padding:16px; text-align:center; color:#ff5555\">无法连接至开发板端侧服务</td></tr>';});}function sd"
    "cardGoPath(path) {curSdPath = path.startsWith('/') ? path : '/' + path;sdcardRefreshList();}function"
    " sdcardGoUp() {if (curSdPath === '/' || !curSdPath) return;const parts = curSdPath.split('/').filter"
    "(Boolean);parts.pop();curSdPath = '/' + parts.join('/');sdcardRefreshList();}function sdcardMkdir() "
    "{const name = document.getElementById('newDirName').value.trim();if (!name) return;const targetPath "
    "= (curSdPath === '/' ? '' : curSdPath) + '/' + name;fetch('/api/sdcard/mkdir', {method: 'POST',heade"
    "rs: {'Content-Type': 'application/json'},body: JSON.stringify({path: targetPath})}).then(r => r.json"
    "()).then(d => {if (d.success) {document.getElementById('newDirName').value = '';sdcardRefreshList();"
    "} else {alert('创建目录失败: ' + (d.error || '权限或路径非法'));}}).catch(e => alert('请求失败'));}function sdcardUpl"
    "oadText() {const fname = document.getElementById('uploadFileName').value.trim();const content = docu"
    "ment.getElementById('uploadFileContent').value;if (!fname) {alert('请输入目标文件名');return;}const targetPa"
    "th = (curSdPath === '/' ? '' : curSdPath) + '/' + fname;fetch('/api/sdcard/upload', {method: 'POST',"
    "headers: {'Content-Type': 'application/json'},body: JSON.stringify({path: targetPath, content: conte"
    "nt})}).then(r => r.json()).then(d => {if (d.success) {alert('✅ 文件已成功保存至 TF 卡: ' + targetPath);docume"
    "nt.getElementById('uploadFileName').value = '';document.getElementById('uploadFileContent').value = "
    "'';sdcardRefreshList();} else {alert('保存失败: ' + (d.error || '写入错误'));}}).catch(e => alert('上传异常'));}"
    "function handleLocalFileSelected(input) {if (input.files && input.files[0]) {const file = input.file"
    "s[0];document.getElementById('uploadFileName').value = file.name;const reader = new FileReader();rea"
    "der.onload = function(e) {document.getElementById('uploadFileContent').value = e.target.result;};rea"
    "der.readAsText(file);}}function sdcardDelete(path, isDir) {const typeStr = isDir ? '目录' : '文件';if (!"
    "confirm(`确认永久删除该${typeStr}：\\n${path} ？`)) return;fetch('/api/sdcard/delete', {method: 'POST',header"
    "s: {'Content-Type': 'application/json'},body: JSON.stringify({path: path})}).then(r => r.json()).the"
    "n(d => {if (d.success) {sdcardRefreshList();} else {alert('删除失败: ' + (d.error || '请确认目录是否为空'));}}).c"
    "atch(e => alert('删除请求异常'));}// 初始化加载 TF 卡文件列表sdcardRefreshList();</script></body></html>";

const char *phoenix_web_asset_get_setup_html(void)
{
    return s_setup_html;
}

size_t phoenix_web_asset_get_setup_html_len(void)
{
    return sizeof(s_setup_html) - 1;
}

const char *phoenix_web_asset_get_dashboard_html(void)
{
    return s_dashboard_html;
}

size_t phoenix_web_asset_get_dashboard_html_len(void)
{
    return sizeof(s_dashboard_html) - 1;
}
